nextcloud/news

docs/externalapi/External-Api.md

The spec sometimes says isRead and sometimes isUnread.
Change everything to isUnread so full and reduced items use the same name.

Consistently use isUnread in item json

---

lib/Db/Feed.php

Instead of the array return type use component parameter PHP_URL_HOST
to get the host part from the URL as string. This avoids an undefined
index warning if host part could not be found.

Implementation for issue https://github.com/nextcloud/news/issues/38

---

appinfo/database.xml
appinfo/info.xml
composer.json
lib/Db/Item.php
lib/Fetcher/FeedFetcher.php
lib/Service/FeedService.php
tests/Unit/Controller/ExportControllerTest.php
tests/Unit/Db/ItemTest.php
tests/Unit/Fetcher/FeedFetcherTest.php
tests/Unit/Service/FeedServiceTest.php

Implement your suggestions from https://github.com/owncloud/news/issues/982#issuecomment-213811774
* update picoFeed to 0.1.25
* add updated_date to the database
* use the new getPublishedDate and getUpdatedDate from picoFeed to set the corresponding item values
* adjust the unit tests

Add updatedDate to item model

---

tests/Unit/Db/MapperTestUtility.php

getMock() is deprecated since phpunit 5.4

Use createMock() instead of deprecated getMock()

---

lib/Service/ItemService.php
tests/Unit/Service/ItemServiceTest.php

Fix for #58 
Also add a test case for this

Throw ServiceNotFoundException when marking non-existent item as read

---

lib/AppInfo/Application.php
lib/Config/AppConfig.php

nc11 finally removed the 3 year+ deprecated api
cc @BernhardPosselt

use non deprecated public api to register background job

---

README.md

Fixed link to code for Android sync client from non-existent Nextcloud repo to actual Owncloud repo

Fixed broken link for sync client in README

---

README.md

In https://github.com/nextcloud/news/commit/004fcbbcc7609ca83807f2e38967ef54f469bf72#diff-d9c8edc6e6e9557c91d113ede10ef894 the directory layout has been updated, but unfortunately it was forgotten to update the link for the new layout.

Correct link to "background_job_file"

---

templates/part.navigation.feed.php

As I said in the issue, "mark read" is the most used menu item, and it must be the first, that way we will drag the mouse less.

Fix for #156

---

templates/part.content.explore.php
templates/part.content.shortcuts.php

Fix include statement in some templates from `part.content.cronwarning.php` to `part.content.warning.php` (see #166 ).

Fix include of “warning” template

---

lib/Service/StatusService.php

Instead of the buggy StatusService->hasIncorrectCharset, use
the already available IDBConnection->supports4ByteText() to
determine if 4byte unicode is supported.
Haven't ran unit tests on this one yet, because 'make test' bombs on me (PHP Fatal error:  Trait 'OCA\News\Controller\JSONHttpError' not found in /home/gmc/src/3rdparty/nextcloud/nextcloud-git/apps/news/tests/Unit/Controller/JSONHttpErrorTest.php on line 18).

Fix #163, use IDBConnection->supports4ByteText()

---

.travis.yml

The issue with mysql on trusty containers has been solved, so we can switch the tests to use trusty and postgresql 9.6

Use trusty and postgresql 9.6 on travis

---

.travis.yml

Using headless mode firefox doesn't need xvfb anymore.
Headless mode is available since ff 55 which is in
beta right now, so use latest-beta until released.

Use firefox in headless mode on travis

---

Makefile

* Only run `composer update` (seems unnecessary to run both install & update, but maybe I'm missing something)
* Check if npm is available and show an error if not
* Set composer variable also when using a locally download version so we can use `$(composer)` in both cases
* Use `$(MAKE)` instead of `make`
* Use simply expanded variables, which means they only get evaluated once on definition and not on every use.

Misc makefile fixes

---

CONTRIBUTING.md

Fixed camelCase and PascalCase as their meaning was inverted in CONTRIBUTING

Fixed camelCase and PascalCase meaning

---

lib/Explore/feeds/feeds.de.json

- Add: http://t3n.de/rss.xml as new discoverable source for tech news
- Add: https://netzpolitik.org/feed/ as source for network politics / news source
- See also: #240

Add: German Feeds for t3n.de and netzpolitik.org

---

Makefile

After #295 this would help to avoid the issue in the future and should package it properly on macOS and Linux 😉

Allow to package the app on macOS

---

.travis.yml
appinfo/info.xml
css/app.css
css/content.css
js/app-inject-14.js
js/app/App.js
js/directive/NewsScroll.js
js/gui/KeyboardShortcuts.js
js/package-lock.json
js/package.json
templates/index.php

New layout fix, scrolling and keyboard shortcuts fixes

---

composer.json
lib/Db/Feed.php
lib/Db/Folder.php
lib/Db/Item.php
lib/Service/FeedService.php
lib/Utility/OPMLExporter.php
tests/Integration/Fixtures/FeedFixture.php
tests/Integration/Fixtures/FolderFixture.php
tests/Integration/Fixtures/ItemFixture.php
tests/Unit/Controller/EntityApiSerializerTest.php
tests/Unit/Controller/ExportControllerTest.php
tests/Unit/Controller/ItemApiControllerTest.php
tests/Unit/Db/FeedTest.php
tests/Unit/Db/FolderMapperTest.php
tests/Unit/Service/FeedServiceTest.php
tests/Unit/Utility/OPMLExporterTest.php

I had a look through some code here looking for some improvements.
So I want to propose to add own setters and getters to our entities to get rid of those magic calls inside the NC Entity. This also gives us the ability to define request and response types once we are switching to PHP7 like the current master of NC does.
I would like to see what others think about this change. If it is about to be accepted I would also add the methods for the remaining entities.

Entity setters + getters

---

Makefile

They get stripped by the server anyways which makes the integrity check
fail.
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

Do not ship .htaccess files

---

css/content.css

Hello, this PR is an attempt to address [this issue](https://github.com/nextcloud/news/issues/115).
For compact view it makes the header of opened articles 'sticky' so that as you scroll down, the title bar for expanded articles remains in view for easy access to the action buttons (favorite/keep unread/etc).
It will work in Chrome and FF and should also work in Safari and Edge, but it won't work in IE.
There are a couple of other front-end issues labelled as help wanted that I would like to tackle, I picked this as an easy one to get my feet wet.

Feature: make compact mode headers sticky

---

appinfo/app.php
tests/Unit/Config/ConfigTest.php
tests/Unit/Controller/AdminControllerTest.php
tests/Unit/Controller/ExportControllerTest.php
tests/Unit/Controller/FeedApiControllerTest.php
tests/Unit/Controller/FeedControllerTest.php
tests/Unit/Controller/FolderApiControllerTest.php
tests/Unit/Controller/FolderControllerTest.php
tests/Unit/Controller/ItemApiControllerTest.php
tests/Unit/Controller/ItemControllerTest.php
tests/Unit/Controller/PageControllerTest.php
tests/Unit/Controller/UserApiControllerTest.php
tests/Unit/Controller/UtilityApiControllerTest.php
tests/Unit/Db/FolderMapperTest.php
tests/Unit/Db/MapperTestUtility.php
tests/Unit/Fetcher/FeedFetcherTest.php
tests/Unit/Fetcher/FetcherTest.php
tests/Unit/Fetcher/YoutubeFetcherTest.php
tests/Unit/Service/FeedServiceTest.php
tests/Unit/Service/FolderServiceTest.php
tests/Unit/Service/ItemServiceTest.php
tests/Unit/Service/ServiceTest.php
tests/Unit/Service/StatusServiceTest.php
tests/Unit/Utility/ProxyConfigParserTest.php
tests/Unit/Utility/UpdaterTest.php

I just searched for some cases where we are still using classname strings and replaced those with magic class constants to improve code style a bit, even if those are basically just test files :grinning:

Use magic class constant

---

lib/Command/Updater/AllFeeds.php

I wish to implement in https://github.com/nextcloud/news-updater a folder based update time, since I have a large number of feeds but only a few of them requires to be updated very often.
Hence in order to be able to do that I need that "news:updater:all-feeds" returns also the folderId.
Of course this is not only for personal usage and if this patch will be accepted I planned to create a pull request also to the news-updater.
I think this is very simple patch that shouln't cause any issue, but if it does please let me know what they are, and if I can fix them.

Return also folderId with "news:updater:all-feeds"

---

css/content.css

Change CSS "height" for a "min-height" so that it can expand if necessary
Fixes #359

Fix multi-line news titles

---

lib/Config/LegacyGuzzleResponse.php

Fix #413 
Works  with feed-io 3 (getHeader() returns an array) and will works with feed-io 4 (getHeader() returns an iterator)

#413 DateTime::createFromFormat()

---

templates/index.php

- when opening news app on lower end computer, the angular templates
flash on the screen for about 1 second
- angular directive doc: https://docs.angularjs.org/api/ng/directive/ngCloak

prevent raw angluar templates from flashing on page load

---

Makefile

Suspecting an outdated dependency got shipped in 13.1.1, this should prevent that from happening in the future.

Have dist also reinstall dependencies

---

lib/Fetcher/FeedFetcher.php

When updating feeds the modified since date is added as a filter. This needs to be reset when looping over the feeds. Fixes #444.

reset modified since filter when updating feeds

---

css/content.css

Fixes the lack of background on the news item title when scrolling, which makes the content unreadable and defeats the idea of the sticky title (#450), by putting the colour back that was removed in e4da0957.

Put background back on news title

---

appinfo/info.xml
composer.json

What about the other dependencies?
And i saw that guzzle was added to the dependencies. Do we actually need that or can we move it back to require-dev?

info.xml: bump php min-version

---

composer.lock

This will partially-fix #430 as it reintroduces sensibility for the 'content:encoded' tag.
It will not re-implement the full text feature :)

restore full text for rss feeds that contain a 'content' tag

---

css/navigation.css
templates/part.navigation.addfeed.php

Since the BasicAuth credentials were the only "Advanced settings", i removed the `Advanced settings` Button and added a `credentials` Checkbox instead.
This change makes the interface clearer.
Technically, the `Advanced settings` string is not used anymore. I didn't delete the transaltions yet. 
Should I?

UI: Make BasicAuth Credentials less important in subscription form (but also visible)

---

lib/AppInfo/Application.php

https://github.com/nextcloud/news/pull/485#issuecomment-481607040

Use nextclouds temp dir

---

lib/Service/StatusService.php
templates/part.content.warnings.php

According to #496 first I just removed the notification from the frontend. How are the translations removed - have I to remove them or is Transifex removing unused translations?
We still have an API request returning a flag for this. For BC we are not able to remove this flag, but I'm not sure if we should just keep it or return false in every case and update the documentation?

Remove UTF-8 charset warning from news

---

css/app.css
css/mobile.css
js/controller/NavigationController.js
lib/Controller/FeedController.php
templates/part.content.php

Fixes https://github.com/nextcloud/news/issues/469
Added a floating button that only shows in "mobile mode". This button will mark the items in the current feed or folder view as read.
Probably will want to make the button itself prettier.
Signed-off-by: nachoparker <nacho@ownyourbits.com>

add "mark read" floating button mobile. Fixes #469

---

templates/part.navigation.feed.php

It makes the menu hard to use to unusable on mobile / tablet
Before
After

prevent menu actions from collapsing sidebar

---

lib/Config/FetcherConfig.php

Some firewalls block requests without the Accept header on the HTTP(s) request as seen on issue #517,
so, just add the header to all requests and say we accept anything.

Add the 'Accept' header to the request

---

.travis.yml
appinfo/info.xml
composer.json
composer.lock
lib/Fetcher/Client/FeedIoClient.php
lib/Fetcher/Client/LegacyGuzzleClient.php
lib/Fetcher/Client/LegacyGuzzleResponse.php

I don't have the intention to merge this right now but I was in the mood to do something:
- update to php 7.1
- nextcloud 16 will require php 7.1
- feed-io 4+ requires 7.1
- updated feedio to 4.3 and adjusted the code
- updated the other packages to the latest version that works with php 7.1
- ~~updated js dependencies~~
-  ~~gulpfile needed adjustments~~
-  ~~uglify replaced by terser~~
~~It might make sense to split this into more than one pr :)~~

Update to feedio4 and php 7.1

---

README.md

Fiery Feeds has recently gained support for Nextcloud News.

Add Fiery Feeds to list of sync clients

---

composer.json
composer.lock
lib/AppInfo/Application.php
lib/Command/ShowFeed.php
lib/Fetcher/FeedFetcher.php
lib/Fetcher/Fetcher.php
lib/Fetcher/IFeedFetcher.php
lib/Fetcher/YoutubeFetcher.php
lib/Scraper/IScraper.php
lib/Scraper/Scraper.php
lib/Service/FeedService.php
tests/Unit/Fetcher/FeedFetcherTest.php
tests/Unit/Fetcher/YoutubeFetcherTest.php
tests/Unit/Service/FeedServiceTest.php

I have reimplemented full-text scraping using this library:
https://github.com/andreskrey/readability.php
What do you think about this?

Reimplement full-text scraping

---

lib/Fetcher/FeedFetcher.php
tests/Unit/Fetcher/FeedFetcherTest.php

Fix #588 
LastModified is used (in a feed context to see if a user edited a feed). httpLastModified to store the last-modified response from the source.
Without the patch the `http_last_modified` value is not longer updated hence updates for feeds will always request the whole data.
https://github.com/nextcloud/news/blob/becce6b7520912257c3d72697a3aefec9923a467/lib/Db/NewsMapper.php#L39-L49
`last_modified` seems to be a field to track changes for a record. `http_last_modified` is the field for the lastmodified timestamp.

Update httpLastModified from the feed response

---

AUTHORS.md
CHANGELOG.md
appinfo/info.xml
composer.json
composer.lock

Will be rebased once #594 is merged.
- Minimum PHP version is now 7.2
- Reimplement full-text scraping #563
- Update for nextcloud 18 #593 #583
- Update httpLastModified from the feed response #594

Release 14.1.0

---

AUTHORS.md
CHANGELOG.md
appinfo/info.xml

Changed
- feed-io updated to v4.5.1 #613
- Automatically convert youtube channel urls in feed url #612
Fixed
- Scraper breaks feed fetching when it fails #606

Release 14.1.1

---

README.md

Delete no longer maintained sync clients, amazingly most of them are still available and even getting updated.

Delete clearly discontinued sync clients

---

appinfo/database.xml
docs/plugins/README.md
lib/Db/Item.php
lib/Fetcher/FeedFetcher.php
templates/part.content.php
tests/Integration/Fixtures/ItemFixture.php
tests/Unit/Controller/ExportControllerTest.php
tests/Unit/Db/ItemTest.php

This is an attempt to tackle #570 
This adds support for media thumbnails and description, available since Feedio 4.5.
Now youtube feeds display correctly:
I am not a PHP expert, neither an angular one, so I am not really used to good practices with those tools. Do not hesitate to tell me if there is anything I can improve.

Basic Media-RSS support

---

composer.json
composer.lock

Fix: https://github.com/nextcloud/news/issues/621, Fix: https://github.com/nextcloud/server/issues/19480

Don't install symfony/console via composer

---

appinfo/database.xml

Close #510
Hopefully this will solve performance with MySQL/MariaDB.
There is no way to prove this though. See #510

Index improvements

---

.travis.yml
lib/Db/FeedMapper.php

This is a different approach to #80 .
Here, we apply the aggregate functions in a subquery and get the defails from the `feeds` table in the outer query. 
This makes it easer to see what we are counting and by what we are grouping by. Also, we don't have to include every column from `feeds` in the `group by`.
This uses subqueries rather than a `with` clause as MySQL only supports that in version 8 upwards.
Also, the table of origin has been added to `unread`, as all other columns are referenced this way.
This PR is meant to be an alternative to #406 in consultation with @Grotax to put both ways up for discussion.

Different solution for ONLY_FULL_GROUP_BY (see #406) (Issue #80)

---

lib/Service/FeedService.php
tests/Unit/Service/FeedServiceTest.php

and we are unable to continue because there is no valid feed data
Ref #640

Check if $feed is null

---

js/app/Config.js
js/app/Run.js
lib/Db/FeedType.php
lib/Db/ItemMapper.php
templates/part.navigation.unreadfeed.php

The "Unread articles" folder will always be visible, regardless of the "Show all" setting. If that setting is on, then an additional "All articles" folder will be show as before, but it doesn't substitute the "Unread articles" one.
A new URL /apps/news/#/items/unread is also created that jumps to the unread articles.
I think this should fix issues #629, #534, #508, #310, #287, #248, at least to some extent.

Always show the unread articles "folder"

---

js/controller/NavigationController.js
templates/part.navigation.unreadfeed.php

Since they shared the same function the "Unread" and "All" menu items were marked active at the same time.
Also the reload of the "Unread" by clicking it or pressing `r` didn't work. (fixes #671, fixes #673)

fixed active menu item and reload for unread

---

appinfo/info.xml
composer.lock
js/package-lock.json

Didn't update the version in the xml file with the release.
Also did a run of npm audit fix reducing the open vulnerabilities by 415 out of 420.

bump version and npm audit fix

---

README.md

I added the Readrops Android client that supports Nextcloud News to the client list.

Added Readrops Android client to client list

---

README.md

Since it powers such a large part of the app, this should be added IMHO

Add sponsor note about Feed-IO

---

lib/Explore/feeds/feeds.en.json

https://regimental-standard.com/
Warhammer 40K themed newsletter providing humorous and uplifting news bulletins for the Imperial Guardsmen of the 42nd millenium.

Add feed: The Regimental Standard

---

lib/Explore/feeds/feeds.en.json

As unfortunate as it is, John "TotalBiscuit" Bain passed away in 2018, with the last video uploaded to his channel being posted close to a year ago at this point. It is probably best to open up space for other feeds.

Remove Totalbiscuit from Explore

---

lib/Db/Item.php

The 'str_replace' will match any HTML element that starts with '<a',
including things like '<address' or '<article', thus creating spurious
links in item bodies. Fix that by simply adding one whitespace.
Fixes issue #527.

Do not create spurious links in item body

---

lib/AppInfo/Application.php

As a followup for https://github.com/nextcloud/news/issues/477
I setup a local copy of nextcloud news to configure it properly.
I also researched a bit on the security side of it and I think it is pretty safe as browsers will block attempts to use data URIs for phising attacks
https://en.wikipedia.org/wiki/Data_URI_scheme#Malware_and_phishing

Allow data URI scheme inside the body of an item.

---

appinfo/info.xml
js/admin/Admin.js
lib/Config/Config.php
lib/Controller/AdminController.php
lib/Cron/Updater.php
lib/Settings/Admin.php
templates/admin.php
tests/Unit/Controller/AdminControllerTest.php

I investigated #643 again and figured out that the way we defined our background job is probably no longer valid.
So I tried to implement the new way.
Interesting side effect of this is that we are no longer depending on the cron update interval but that the interval to update the feeds can be set in the settings, not individually per feed or user but system wide.
I still think that this would be an cool addition to news and allow people to reduce the amount of traffic they cause, as the new default for nextcloud is every 5min every 30min would probably be enough for most people.
This PR is marked as draft as documentation is still missing and I'm not that confident about my code.
I tried my best though (actually I'm more of an python developer :D) 
Tests are running and I installed it in …

Update to new BackgroudJob logic

---

README.md

FeedReader has been archived: https://github.com/jangernert/FeedReader/
The author has started working on a successor called NewsFlash, which currently doesn't support Nextcloud's News: https://gitlab.com/news-flash/news_flash_gtk
Quote from the README:
> Some services supported by FeedReader have not yet found their way into NewsFlash. Work for Google Reader style APIs is already on the way (FreshRSS, InoReader, The Old Reader). **Nextcloud News will probably only happen as soon as their [APIv2 draft](https://github.com/nextcloud/news/blob/ec3cc602f1bd363efe776ce4914319034d35c18e/docs/externalapi/External-Api.md) gets implemented.**

Removes FeedReader from Sync Clients list

---

lib/Explore/feeds/feeds.de.json

Tarnkappe.info is a german news page about privacy.

Update feeds.de.json and add Tarnkappe.info

---

lib/Fetcher/FeedFetcher.php

Fix crash if full-text is enabled and the news item does not provide an URL to be fetched

---

lib/Explore/feeds/feeds.de.json

According to their website, the RSS2 feed seems to be preferred and has images etc, which the Atom feed does not have.
This is a duplicate of #779 because I didn't know about Signed-off-by and I'm too lazy to figure out how to edit my commit message.
Signed-off-by: felurx

Add tagesschau.de to feeds.de.json

---

composer.lock
lib/Config/Config.php
tests/Unit/Config/ConfigTest.php

PHPCBF complained about a whitespace, no idea where it sees a whitespace in that line 
```
FILE: /home/grotax/git/nc-server/apps/news/lib/Config/Config.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
202 | ERROR | [x] Whitespace found at end of line
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```

fix config test

---

css/content.css

When loading content background-color should be set from theme.
I'm pretty sure this wasn't an issue before but I've no idea when or where it was introduced, so it might affect more than just the background when loading articles.

Fix background color when loading content

---

lib/Controller/PageController.php

When calling the news URL while not logged in it causes an Internal server error since the `$UserId` is null.
For example https://cloud.example.com/apps/news/#/items/unread should redirect to the login page instead of crashing.

fix invalid UserId when logged out

---

lib/Command/Updater/AfterUpdate.php

The news:updater:after-update tries to load the wrong argument, hence it fails

Fix 'news:updater:after-update' command

---

lib/Db/ItemMapperV2.php
lib/Service/ItemServiceV2.php

The old way of updating items seems better as mentioned in https://github.com/nextcloud/news/issues/827#issuecomment-703149126, so I've adopted it.
The line
```php
$db_item->setBody($item->getBody());
```
may have some side effects with the following, but they should have been there already until now.
https://github.com/nextcloud/news/blob/b17f1ca26de1a4c69a1f398cfd781847806d0f45/lib/Db/Item.php#L316-L318
Fixes #827

update only relevant item fields

---

Makefile
bin/tools/file_from_env.php

To prevent the shell from reading the key/crt and doing interpretation :roll_eyes: I wrote a small php script.
It takes an environment variable name and a file path to write the content of that variable to that file.

Add file_from_env.php

---

.github/workflows/build-release.yml
Makefile

The last release failed due to the path was missing, where the key and cert are normally stored.
Also enabled the upload the app store and replaced the fake secrets, with the actual secrets.
I think we are almost there :)

Automate release

---

.github/workflows/php-tests.yml
CHANGELOG.md
composer.lock

This adds the upload of the code coverage after a run of the unit tests.
We did have this with travis and it got lost in the migration to Github Actions
Should I rather create an extra job instead of using the existing one?

Upload codecoverage to codecov.io

---

.github/dependabot.yml

According to the [Dependabot docs](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#labels) the labels are configured slightly different. This also matches the error visible in the 'Insights'.
```
The property '#/updates/0/' contains additional properties ["default_labels"] outside of the schema when none are allowed
The property '#/updates/1/' contains additional properties ["default_labels"] outside of the schema when none are allowed
```

update dependabot label config

---

lib/Command/Updater/AllFeeds.php

This fixes a bug when calling allfeeds by hand about not returning anything which makes the generated json unuusuable with errors appended to stdout.
TypeError: Return value of "OCA\News\Command\Updater\AllFeeds::execute()" must be of the type int, "null" returned. in apps/mail/vendor/symfony/console/Command/Command.php:261
Returning "no error/0" fixes it.

Return expected Value for Symfony Commands

---

Makefile

xDebug which is used by phpunit to do code coverage tests, introduced some breaking change in 3.0 and requires this env-var to be set.
Shouldn't break anything for older versions

fix xDebug 3.0

---

README.md

Removes the Travis badge and replaces it with the Frontend test action.
~~Somehow it currenty still states "no status". I hope this will be solved if it runs the next time.~~

update frontend test badge

---

CHANGELOG.md
lib/Db/NewsMapperV2.php
lib/Fetcher/FeedFetcher.php
lib/Service/ItemServiceV2.php
tests/Unit/Fetcher/FeedFetcherTest.php

We remove the call to `readSince()` as some feeds push new articles with
`pubDate` prior to the `lastModified` time stored for these feeds (_e.g.
lemonde.fr_). As we go through all items of a feed again and again, we
prevent the constant update of an item's `lastModified` timestamp by
keeping the previous one if its fingerprint does not change.
Feel free to comment if this change is missing something as I'm a new user/contributor to this project :)
Also I don't know if `generateSearchIndex()` is an optimal way here to compute the fingerprint of the fetched item, `computeFingerprint()` and `computeContentHash()` being private methods.
Fixes #921

Remove LastModified-based cursor when updating feeds

---

CHANGELOG.md
css/content.css

~~Unfortunately I was not able to test this only in my dev tools, since I wasn't able to set up a dev environment.~~ Got it working.
This adds a background color for uneven entries & a hover effect in compact mode.
Since this targets just the div, this does not interfere with the content when opened.
Pictures:
Basic list:
Hover over blue entry: 
Hover over white entry:
Opened blue & hovered white entry:

compact mode: add background for hover and odd content entries

---

.github/dependabot.yml

According to https://github.com/nextcloud/news/pull/998#issuecomment-749357923 the language specific labels where removed.

update dependabot labels

---

CHANGELOG.md
lib/Db/FeedMapper.php

`Exception: Argument 2 passed to OCA\News\Db\FeedMapper::find() must be of the type int, string given` (#996)
The called function arguments are switched.
https://github.com/nextcloud/news/blob/d542cf5376ca5869d19aa45849428354596d74d2/lib/Db/FeedMapper.php#L38
Got this error multiple times after updating my test instance to 15.1.1-rc2, but don't know what exactly caused this, since my main instance works fine.

fix FeedMapper find exception

---

CHANGELOG.md
appinfo/info.xml

Fixed
- Argument 2 passed to OCA\News\Db\FeedMapper::find() must be of the type int, string given #996

Release 15.1.1

---

CHANGELOG.md
css/content.css

Since introducing the zebra-striped headlines, the subtitle and utility bar spacing was noticably off. This commit fixes that.
Before:
After:

Improve whitespace in compact mode

---

.github/workflows/static-code-check.yml
composer.json
composer.lock
psalm.xml

This adds the static code analyzer psalm based on https://docs.nextcloud.com/server/latest/developer_manual//digging_deeper/continuous_integration.html

Add psalm for static code analysis

---

CHANGELOG.md
lib/Db/FeedMapperV2.php
lib/Db/FolderMapperV2.php
lib/Db/ItemMapperV2.php
lib/Db/NewsMapperV2.php
tests/Unit/Db/FeedMapperTest.php
tests/Unit/Db/FolderMapperTest.php
tests/Unit/Db/NewsMapperTest.php

With NC 21.0 beta5, the dbal dependency was updated from 2.12.0 to 3.0.0, and with it the (deprecated) support for the colon prefix for `->setParameter` has been removed.
- [Deprecation note](https://github.com/doctrine/dbal/blob/3.0.0/UPGRADE.md#deprecated-colon-prefix-for-prepared-statement-parameters)
- [Removal note](https://github.com/doctrine/dbal/blob/3.0.0/UPGRADE.md#bc-break-leading-colon-in-named-parameter-names-not-supported)
Fixes #1030

remove deprecated colon prefix for parameters

---

CHANGELOG.md
lib/Db/ItemMapper.php

`$search` is already handled by `buildSearchQueryPart()` and the third argument is actually a (unused) bool named `$distinctFingerprint`.
fixes #1044
refs #1022

fix TypeError in ItemMapper

---

CHANGELOG.md
lib/Controller/ItemApiController.php
lib/Db/ItemMapper.php
lib/Service/ItemService.php
tests/Unit/Controller/ItemApiControllerTest.php

`$paddedLastModified` needs to be an int later on but was converted to string if shorter than 11 digits.
fixes #1049

fix TypeError caused by type conversion in ItemApiController

---

.github/dependabot.yml

Checks for dependency updates for packages used in workflows (everything after the `uses:` tag).
However I am not sure if we should use the 'dependencies' label there, since it is only an internal dependency here on GH.

add dependency checks for Github actions

---

psalm.xml
tests/psalm-baseline.xml

This sets the current errors in our code as "ok" any additional error in the code will exactly cause that.
run 
```
./vendor/bin/psalm --update-baseline
```
to update the baseline file based on the current code status and raw errors.
`tests/psalm-baseline.xml` lists all the ignored errors and how often they appeared.

ignore current issues but catch new ones

---

.github/workflows/static-code-check.yml
CHANGELOG.md
composer.json
composer.lock
lib/Controller/FeedApiController.php
lib/Controller/ItemApiController.php
lib/Service/FeedServiceV2.php
psalm.xml
tests/psalm-baseline.xml

This will make psalm pass with more v21 code, and clear out some undefined classes issues in the run.

Base: Update psalm definition and dependency list

---

CHANGELOG.md
lib/Command/Updater/AfterUpdate.php
lib/Db/ItemMapperV2.php
lib/Service/ItemServiceV2.php
tests/Unit/Command/AfterUpdateTest.php

Implement missing Mapper feature

Mappers: Implement item purging

---

CHANGELOG.md
appinfo/info.xml

Changed
You can now delete unread items via occ:
`occ news:updater:after-update --purge-unread [<purge-count>]`
Fixed
- Item purger does not work with PostgreSQL (#1094)
- Export starred/unread correctly (#1010)

Release 15.2.0

---

.github/workflows/build-release.yml
CHANGELOG.md

The signature.json file was not created, which is very obvious but we missed that when we introduced the automation.
This uses the Nextcloud action we already used to clone the server, set it up, copy the news app into the server, build and sign it.
Example: https://github.com/Grotax/news/releases/tag/15.2.13
appinfo/signature.json
Related
https://github.com/nextcloud/documentation/pull/6001
#1117

Release: create signature file (#1117)

---

.github/workflows/api-php-static-code-check.yml

This removes the psalm run for stable20 as it crashes for some reason.
I also think if we want to support multiple versions of NC to detect comparability issues with psalm, we need to run the install of christophwurst/nextcloud dynamically, that was dropped in #1125

remove stable20 from psalm run

---

.github/workflows/api-integration-tests.yml

This enforces the enabling of news on pre-release (aka master) versions of nextcloud.
Which allows us to test on NC22 while we don't mark news as compatible to NC22.
We had the issue in the past that we would already enable the app for the next version of nextcloud to be able to test it, but meanwhile we would release another patch to the app store, including the enabling of NC22 for example.
Working with branches would be an alternative but I think this makes more sense for us.

Actions: force enable app on pre-release versions

---

lib/Db/ItemMapperV2.php
tests/Unit/Db/ItemMapperTest.php

Follow-up for b4fa772bc5f23f84fc292f5d6bf884543d2bfe51 because of the `updated_date` which was removed in the meantime.
It will require a corrected `last_modified` value for the items before the next release..

update sorting column

---

.github/workflows/api-integration-tests.yml
CHANGELOG.md
lib/Command/ShowFeed.php
lib/Fetcher/FeedFetcher.php
lib/Fetcher/Fetcher.php
lib/Fetcher/IFeedFetcher.php
lib/Service/FeedServiceV2.php
tests/Unit/Command/ShowFeedTest.php
tests/Unit/Fetcher/FeedFetcherTest.php

This changes the behavior of fetching the favicon, since feed-io offers to get the feeds logo, we try to get that first, then fall back to the favicon.
I didn't change the var name, I'm not sure if we should do that. But that would include API changes if I'm not wrong.
Also I want to test this first.

FeedFetcher: Use feeds logo instead of the favicon

---

composer.lock
lib/Command/ShowFeed.php
lib/Fetcher/FeedFetcher.php
lib/Fetcher/Fetcher.php
lib/Fetcher/IFeedFetcher.php
lib/Service/FeedServiceV2.php
tests/Unit/Command/ShowFeedTest.php
tests/Unit/Fetcher/FeedFetcherTest.php
tests/Unit/Fetcher/FetcherTest.php

This removes lastModified from the Fetcher as it is no longer used since 42ea24f2f41ce04588aa929e5ffdaf1dbeb1a700
The original idea of lastModified was to reduce the amount of data news pulls from servers by checking the http header but that turned out to skip certain items in feeds ...
ref #975

remove unused lastModified from feed fetcher

---

README.md
docs/faq/README.md

Add a documentation of the `occ news:updater:after-update` command to the FAQ. So far the command has only been mentioned in the release notes.
The command provides a manual workaround for the problems mentioned in #110.

Add documentation for manual purging of unread items

---

CHANGELOG.md
js/controller/ContentController.js
js/tests/unit/controller/ContentControllerSpec.js
templates/part.content.php

fixes #1147 
Rather than using Angular's built-in comparison on the `id` field, we need to parse them as integers first. Otherwise, they get compared alphabetically, and the sorted order can end up like 1, 101, 2, 3, etc. (1 comes before 2, and
the comparison stops there.)

Fix id sorting bug

---

CHANGELOG.md
lib/Controller/FeedController.php
tests/Unit/Controller/FeedControllerTest.php

Feed: Fix rename moving file

---

CHANGELOG.md
appinfo/info.xml

Changed
- Remove outdated item DB code. ( #1056)
- Stop returning all feeds after marking folder as read. (#1056)
- Always fetch favicon (#1164)
- Use feed logo instead of favicon if it exists and is square (#1164)
- Add CI for item lists (#1180)
Fixed
- Item list throwing error for folder and "all items" (#1180)
- Articles with high IDs can be placed lower than articles with low IDs (#1147)
- Feeds are accidentally moved on rename (#1189)
- Item list not using ID for offset (#1188)

Release 15.4.0-beta1

---

CHANGELOG.md
lib/Db/ItemMapperV2.php
tests/Unit/Db/ItemMapperPaginatedTest.php

DB: Fix offset quotes

---

.editorconfig
.github/workflows/api-integration-tests.yml
CHANGELOG.md
lib/Command/Config/FolderAdd.php
tests/integration/explore.bats
tests/integration/feeds.bats
tests/integration/folders.bats
tests/integration/helpers/settings.bash
tests/integration/items.bats
tests/integration/opml.bats

Do integration tests in bats instead of just running a script

Actions: Integration tests using bats

---

CHANGELOG.md
lib/Db/Item.php
lib/Fetcher/FeedFetcher.php
lib/Migration/Version150302Date20210312231251.php
tests/Unit/Db/ItemTest.php
tests/Unit/Fetcher/FeedFetcherTest.php

**Authors** : Jimmy HUYNH (@LinkJim) - Marco NASSABAIN (@mnassabain)
Import related tags for each article
- Could be useful to sort articles by tags (in future...)
- Could be integrated in front-end to show keywords
- Could be used to generate hashtags for sharing on social media (e.g.: Twitter)
- UX / UI Friendly !
We are already working on sharing articles with users and on social media. (pr existants)
In case of sharing articles on social medias, we thought that sharing posts, would be more relevant if hashtags were automatically generated. Being that generating tags based on a text is a complex problem, we would use the tags retrieved from the RSS feeds instead.
This is an example of usage that the newly added "tags" field would offer. But we think that there are surely more …

Feature: Import related tags to articles (Categories)

---

.github/workflows/build-release.yml

Due to security questions in the related documentation PR, that I will not link here for now, the Nextcloud team would prefer a pined sha to make sure the code can't change (unless someone manages a sha1 collision).

Switch to sha1 for more security

---

CHANGELOG.md
lib/AppInfo/Application.php
lib/Search/FolderSearchProvider.php

This adds folder search to the unified search.
@nextcloud/news and @nextcloud/designers any opinions on what should be searchable in news? I'm currently thinking just feeds and folders.

Search: Add folder search

---

CHANGELOG.md
appinfo/info.xml
lib/Command/Debug/FeedRead.php
lib/Command/Debug/FolderRead.php
lib/Command/Debug/ItemRead.php
lib/Db/FeedMapperV2.php
lib/Db/FolderMapperV2.php
lib/Db/ItemMapperV2.php
lib/Service/FeedServiceV2.php
lib/Service/FolderServiceV2.php
lib/Service/ItemServiceV2.php
tests/Unit/Db/FeedMapperTest.php
tests/Unit/Db/FolderMapperTest.php
tests/Unit/Db/ItemMapperAfterTest.php
tests/Unit/Db/ItemMapperPaginatedTest.php
tests/Unit/Db/ItemMapperTest.php
tests/Unit/Db/MapperTestUtility.php
tests/integration/feeds.bats
tests/integration/folders.bats

DB: Updates should use set()

---

CHANGELOG.md
js/controller/NavigationController.js
js/service/FeedResource.js
js/tests/unit/controller/NavigationControllerSpec.js
lib/Controller/FeedController.php
lib/Service/FeedServiceV2.php
templates/part.navigation.addfeed.php

This change adds a button to allow for directly adding a a feed by URL, bypassing feed-io's discovery process.  This is useful when a user knows a feed URL, but the discovery process causes an issue adding it to news. The new button is the + on the right side of the subscribe button.
This solves different problems that I'm having with 2 feeds. (#1226 and #1243).

Allow directly adding a feed without going through the discovery process

---

CHANGELOG.md
appinfo/info.xml

Changed
- Add BATS as integration tests (#1213)
- Update FeedFetcher to import categories from feeds (#1248)
- Update serialization of item to include categories (#1248)
- Make PHPStan stricter (#955)
- Search: Add folder search (#1215)
- Improve test coverage (#1263)
- Allow directly adding a feed without going through the discovery process (#1265)
Fixed
- Do not show deleted feeds in item list (#1214)
- Fix update queries (#1211)

Release 15.4.0-beta3

---

templates/part.navigation.addfeed.php

It's a short form for "automatically discover".
Reported at Transifex.
Signed-off-by: rakekniven <mark.ziegler@rakekniven.de>

Changed spelling of "auto discover"

---

CHANGELOG.md
lib/Fetcher/FeedFetcher.php

Signed-off-by: skiingwiz <skiingwiz@gmail.com>
Using the latest beta, one of my feeds caused an error with the new categories code.  Everything else calling decodeTwice() is checking for null first, so this pull request adds that same logic to the category labels.
The error I was getting without this is:
`"Exception":"Exception","Message":"Argument 1 passed to OCA\\News\\Fetcher\\FeedFetcher::decodeTwice() must be of the type string, null given, called in /var/www/nextcloud/apps/news/lib/Fetcher/FeedFetcher.php on line 261"`

Null check category label before trying to decode

---

CHANGELOG.md
lib/Fetcher/FeedFetcher.php

The content of an Atom feed is missing (probably caused by #1239) after updating to v15.4.0 (reported in the maintainer chat).
Validated for:
- https://en.wikipedia.org/w/api.php?action=featuredfeed&feed=potd&feedformat=atom
- https://rss.golem.de/rss.php?feed=ATOM1.0
- https://xkcd.com/atom.xml
For the master branch it's already fixed with 91db7113a8d844eb7d0e91596f8632e82210b6f6.

fix atom feed summary fetching

---

CHANGELOG.md
composer.lock
lib/Fetcher/FeedFetcher.php
tests/integration/feeds.bats
tests/integration/helpers/settings.bash

Some potential improvements for favcion fetching.

Fix some of the favicon errors

---

CHANGELOG.md
lib/Db/ItemMapperV2.php
lib/Service/ItemServiceV2.php

__Workaround for v15.4.x, further plans regarding 32-bit as of the next major are discussed in #1333.__
Since I'm not sure how the QueryBuilder handles floats like `1.620141854E+15` for bigint fields I've explicitly formated it into a string
```php
number_format($updatedSince, 0, '.', '')
```
Because I don't have any 32-bit OS here, I couldn't test it in depth.

mitigate 32-bit issues with microseconds

---

CHANGELOG.md
appinfo/info.xml

Fixed
- mitigate 32-bit issues by using `float` instead of `int` for microseconds (#1320)

Release 15.4.3

---

CHANGELOG.md
appinfo/info.xml

This relates to https://github.com/nextcloud/news/issues/1320
The most straight forward option we have is to simply require 64bit. 
The biggest impact would be probably that users of small ARM devices can't install newer news versions anymore and have to revert back to 15.3.x.

Require 64 bit integer

---

CHANGELOG.md
lib/Controller/ItemApiController.php
tests/Unit/Controller/ItemApiControllerTest.php

Should fix #1328
Allows people to call `/items?batchSize=-1&getRead=false&type=3`

controller: getRead + all_items is now unread type

---

appinfo/info.xml
templates/admin.php

This updates the links and references to the new documentation.
The old files will stay in this branch, including the readme. But to make the app more usable for users of 15.x the links visible in the app and the appstore get updated.

Update stable15 to new docs

---

CHANGELOG.md

Fixed
- allow calling `/items?getRead=false` without a feed/folder

Release 15.4.4

---

CHANGELOG.md
appinfo/info.xml

Changed
- News now requires a 64bit OS
- v2 API implementation (folder part)
- Implemented sharing news items between nextcloud users (#1191)
- Updated the news items table in DB to include sharer data (#1191)
- Added route for sharing news items (#1191)
- Added share data in news items serialization (#1191)
- Added tests for the news items share feature (#1191)
- Added sharing articles with nextcloud users (#1217)
- Added sharing articles on social media (Facebook, Twitter) or mail (#1217)

Release 16.0.0-beta1

---

mkdocs.yml

This might fix the broken 404 page, apparently when the site-url is missing some things including the 404 page break.
Unfortunately there is no way to test this locally ..

add more meta data to docs

---

CHANGELOG.md
lib/Db/ItemMapperV2.php
tests/Unit/Db/ItemMapperAfterTest.php
tests/Unit/Db/ItemMapperTest.php

This might fix some issues some people/apps have been having.
Most notably: https://github.com/nextcloud/news/issues/1324

db: no longer order by `items.last_modified`

---

.github/workflows/api-integration-tests.yml

As the migrations command is not needed, we can simply drop it
fixes #1389

remove migrations command from ci

---

CHANGELOG.md
appinfo/info.xml

- Allow installation on Nextcloud v22
- Remove deprecated API endpoints and occ comand (#935)
- /api/v1-2/user
- /api/v1-2/user/avatar
- ./occ news:updater:all-feeds
- allow calling `/items?getRead=false` without a feed/folder (#1380 #1356)
- newestId does not return newest ID but last updated (#1339)

Release 16.0.0-beta2

---

CHANGELOG.md
lib/Db/Item.php
lib/Service/ShareService.php

Fixes #1375
When creating a copy of the item to be shared, we set the id to null. The goal of this was to allow the DBMS to automatically generate an id on insertion.
However, everytime an entities field changes, the field is marked as updated. In this case, it's the id field that gets marked as updated. Since Nextcloud has it's own code for persisting entities, it builds an SQL query with all of the updated fields. The result of this operation will be an SQL query explicitly setting the id to null - provoking an error (in some DBMS) since id is not nullable.
The solution is not to mark the id field as updated. As a consequence, the SQL query won't specifically set it to null on persist. The id will instead be generated automatically by the DBMS.
1. First idea: Implement a `duplicate()` …

Fix: NotNullConstraintViolation when sharing with users 

---

CHANGELOG.md
appinfo/info.xml

There are no additional changes compared to the latest beta.
Changed
- News now requires a 64bit OS
- v2 API implementation (folder part)
- Implemented sharing news items between nextcloud users (#1191)
- Updated the news items table in DB to include sharer data (#1191)
- Added route for sharing news items (#1191)
- Added share data in news items serialization (#1191)
- Added tests for the news items share feature (#1191)
- Added sharing articles with nextcloud users (#1217)
- Added sharing articles on social media (Facebook, Twitter) or mail (#1217)
- Allow installation on Nextcloud v22
- Remove deprecated API endpoints and occ command (#935)
- /api/v1-2/user
- /api/v1-2/user/avatar
- ./occ news:updater:all-feeds
- added feed search (#1402)
Fixed
- allow calling `/items?getRead=false` …

Release 16.0.0

---

CHANGELOG.md
js/app/App.js
js/app/VueComponents.js
js/controller/AppController.js
js/gulpfile.js
js/package-lock.json
js/package.json
js/vue_components/IconLinkCompact.vue
js/webpack.config.js
templates/index.php
templates/part.content.explore.php
templates/part.content.php

Also adds related parts for compiling Vue components into the existing Javascript bundle.
This is a cleaned-up version of PR #1246, which was only meant to be an experiment and generate discussion. That PR had a lot of extra commits in it for testing things; this PR has only what is necessary.

Add Vue and ng-vue packages

---

CHANGELOG.md
js/.jshintrc
js/controller/ContentController.js
js/filter/RelativeTimestamp.js
js/gulpfile.js
js/karma.conf.js
js/package-lock.json
js/package.json
js/tests/unit/controller/ContentControllerSpec.js
templates/part.content.php

This PR offers a more complete solution than #1441, and replaces it.
This is a re-implementation of relative date/time formatting (`getRelativeDate()`), which was mentioned in #1433. Original version used NodeJS module `moment.js`, which is obsolete, deprecated, and slated for removal from Nextcloud base.
This version implements relative formatting as a filter, instead of a controller method. It uses pure JavaScript `Intl.RelativeTimeFormat`, with fallback to plain date formatting for older browsers. Dependency on `moment.js` is dropped. The new function is, however, slightly different from the original:
- If the distance between now and the timestamp is more than 90 days (and for older browsers), absolute date/time format is used. I didn't want to use "N months ago" relative format, …

Reimplement relative time formatting as a filter, dropping dependency on deprecated moment.js

---

CHANGELOG.md
appinfo/info.xml
lib/Command/Updater/UpdateUser.php
tests/Unit/Command/UpdateUserTest.php

Closes #1359
This is not at all tested. I'd like feedback about if this feature is desired and if my approach here is the correct one.

Update all feeds from command

---

CHANGELOG.md
css/navigation.css

Just updated to NC 22.1.0 RC1 and in the app navigation the icons and titles are overlapping (caused by nextcloud/server#27936)
| until NC 22.0.0 | since NC 22.1.0 RC1 |
|---|---|
| ![grafik](https://user-images.githubusercontent.com/15173012/127749680-962bdea0-9b06-4835-8a54-0040127d0eaf.png) | ![grafik](https://user-images.githubusercontent.com/15173012/127749675-861bbf8b-4e7b-4eb4-8fb4-cdaa10fdd014.png) |
The changes don't interfere with previous versions (tested on 21.0.3).

explicitly set icon offset in navigation

---

CHANGELOG.md
appinfo/info.xml

Changed
- Reimplemented relative time formatting as a filter (#1450)
Fixed
- Set icon offset explicitly for navigation items (#1465)

Release 16.0.1

---

CHANGELOG.md
templates/part.content.php

The markup for favicon `<img>` element in feed item used `src` instead of
`ng-src`, causing browser to make broken requests for
`.../apps/news/%7B%7B%20::Content.getFeed(item.feedId).faviconLink%20%7D%7D`
Changing the attribute to `ng-src` fixed that.

Fix favicon element making broken requests

---

CHANGELOG.md
appinfo/info.xml

Changed
- Added new `news:updater:update-user` command to update the feeds of a single user (#1360).
Fixed
- Removed spurious requests for `.../apps/news/%7B%7B%20::Content.getFeed(item.feedId).faviconLink%20%7D%7D` (#1488)

Release 16.1.0-beta1

---

CHANGELOG.md
Makefile

This should make the released app 3x smaller.

compiled image: Remove readability tests

---

CHANGELOG.md
lib/Scraper/Scraper.php

recive => receive
While going through my log files trying to debug why my feeds aren't updating anymore, I tried to search/grep for "receive" and was surprised to see no results. Fixing the spelling should make it easier for everyone to search/grep their log files.

Fix spelling of receive

---

CHANGELOG.md
appinfo/info.xml

No notable changes compared to the beta versions.
---
According to the release plan of Nextcloud there will be another release of Nextcloud 20 in November (11.11.21)
https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule
That will probably be the last release of NC20 and it will be EOL.

Release 16.2.0

---

README.md

The [previous link](https://github.com/nextcloud/news/tree/master/docs/externalapi/Legacy.md) throws a 404, so I replaced it with [a link to the current docs](https://nextcloud.github.io/news/developer/#apis)

Fix broken link to Restful API docs in README.md

---

CHANGELOG.md
appinfo/info.xml

Fixed
- Catch network errors while fetching feed logos. (#1572, #1570)
No beta release needed due to the small change

Release 16.2.1

---

.github/workflows/post-merge-tasks.yml

I don't need it anymore, I prefer the integrate function by GitHub.

Remove release drafter

---

CHANGELOG.md
appinfo/info.xml

Changed
- Drop support for Nextcloud 20 (#1514)
- Use better sql commands, that were not possible with Nextcloud 20 (#1514)
- Add support for Nextcloud 23

Release 17.0.0-beta1

---

CHANGELOG.md
css/content.css

Just a small improvement. 
One row is a flex-container so I set a flex-shorthand to make the spacer take up it's width defined by  a bigger width. 
The screen-width limit makes sure the rule only gets applied if the mobile Navigation-Toggle is present.

fix link-icon-overlap in mobile-view

---

CHANGELOG.md
lib/Fetcher/FeedFetcher.php

Display the message instead of the response when catching an exception during feed logo fetching. As there is no response and thus no method `getResponse()` in `ConnectException`, this fixes a "call to undefined method"-error that prevented feeds from fetching if fetching the logo resulted in a `ConnectException`.

Fix catching connect exceptions while fetching feed logos #1570

---

CHANGELOG.md
appinfo/info.xml

Fixed
- Fix catching network errors while fetching feed logos. (#1601)

Release 17.0.1

---

CHANGELOG.md
lib/Controller/FeedApiController.php
tests/Unit/Controller/FeedApiControllerTest.php

I looked at #1544
And investigated the code a bit, it seems like the wrong service was called since we introduced the new controllers.
It didn't throw any errors because both read functions have the same signature but the parameters are used in a totally different way ...
Not tested yet only based on logical reading.

Fix only one item marked as read by Feed API

---

CHANGELOG.md
lib/Controller/FolderApiController.php
lib/Db/FolderMapperV2.php
lib/Service/FolderServiceV2.php

documented: https://nextcloud.github.io/news/api/api-v1/#mark-items-of-a-folder-as-read
Was not implemented according to docs.
Tested with #1699

fix mark items of folder as read

---

CONTRIBUTING.md

Unfortuantely the contribution guide has a wrong URL for FAQ, I haven't found it myself. Found it in https://github.com/nextcloud/news/issues/1702#issuecomment-1071065698
How do I sign of my changes?

Fix FAQ url

---

CHANGELOG.md
lib/Service/ImportService.php

This fixes #1562
The issue with the old logic was that it would create a new feed for each item as the feedLink coming from the json would never exist in the array of feeds.
Because the feed would be added with this placeholder url.
I don't see a need not to use this placeholder url and also no reason to disable updates.
I tested this by adding a feed, exporting the opml and the items.
1. import of items only, creates the feed, just the title is "No Title" as the json does not contain that information.
2. import opml first then items, the feed exists with title and items already before the import, importing the items doesn't cause any problems.

Fix import of items when feed does not exist

---

CHANGELOG.md
lib/Fetcher/FeedFetcher.php
tests/Unit/Fetcher/FeedFetcherTest.php
tests/integration/feeds.bats
tests/integration/feeds/no_guid_feed.xml
tests/integration/helpers/settings.bash

Fixes #1738
Regarding tests, I couldn't find an example on how to implement tests for this feature. I searched for other pull requests but couldn't find any that added a test. This feature would need to fetch a feed from a local file (as currently malformed feeds on the internet may be fixed in the future). If anyone has an example or guidance on how to implement tests for this fix, I'll try to implement them.

Fix malformed feeds (without GUIDs) stopping the update process

---

CHANGELOG.md
lib/Db/FeedMapperV2.php
lib/Db/FolderMapperV2.php
tests/Unit/Db/FeedMapperTest.php
tests/Unit/Db/FolderMapperTest.php

The updated items api is supposed to return updated items, the last modified date is used for that.
I tried to use the $time provided through dependency injection but for some reason it is null.
I don't really care if we can't use dep injection there, if I made a mistake though I would be happy to adjust it.

Fix updated api not returning any item after marking item as read

---

CHANGELOG.md
lib/Db/Item.php

My suggestion to fix #1765 
To keep the functionality the same.

check if variable is null before striping tags

---

CHANGELOG.md
css/content.css

Discussion: https://github.com/nextcloud/news/discussions/1775

Improve styling of tables in articles

---

CHANGELOG.md
js/controller/ContentController.js

Quick update to ContentController.js to correctly set the active element when newest first or default ordering is active for a feed or view.
Should resolve #1324 by making behavior match expectations

GUI Update: Select correct item in feed when loading feed with Newest First or Default Ordering

---

CHANGELOG.md
appinfo/info.xml
docs/api/api-v1-3.md
docs/developer.md
mkdocs.yml

- Add API v1.3 adding routes for starring/unstarring items by id and general fixes (#1727)
https://nextcloud.github.io/news/api/api-v1-3/
- Improve styling of tables in articles (#1779)
- Allow fetching feeds that omit guid by using link as stand-in (#1785)
- Fix updated api not returning any item after marking item as read (#1713)
- Fix deprecation warning for strip_tags() on a null value (#1766)
- Fix selected item being set incorrectly when using default ordering or newest first ordering (#1324)
- Fix doubling the height of the content area (#1796)

Release 18.1.0-beta1

---

CHANGELOG.md
appinfo/info.xml

-  If items of feed do not provide an author fallback to feed author (#1803)

Release 18.1.0-beta2

---

CHANGELOG.md
appinfo/info.xml

Due to #1766 some Feeds might now have items that have `null` set as author instead of `""` clients need to handle this.

Release 18.1.0

---

CHANGELOG.md
appinfo/routes.php

Additionally this enables the CORS and version endpoint for the v2 API (as already documented [here](https://nextcloud.github.io/news/api/api-v2/)).
fixes #1841
~_Currently untested due to missing environment._~
⤷ All api integration tests were successfull, which is probably sufficient.

fix duplicate API routes

---

CHANGELOG.md
lib/Service/FeedServiceV2.php
tests/Unit/Service/FeedServiceTest.php
tests/api/feeds.bats
tests/command/feeds.bats
tests/command/folders.bats
tests/command/items.bats
tests/command/opml.bats

We often get issue reports because some valid feed url is not working due to the autodiscover feature.
The actual reason is of course that the self-reference is wrong and should be fixed by the author.
But I think for news it's easier to just try to parse the feed and if it fails to check again after autodiscover.

Change Autodiscover behaviour

---

CHANGELOG.md
lib/Cron/UpdaterJob.php
lib/Db/NewsMapperV2.php
lib/Migration/Version150005Date20201009192341.php
tests/Unit/Db/NewsMapperTest.php

We were using the OC\ Namespace so I changed that and also checked the docs again and adjusted the code.
the execute() command is deprecated, I also changed it in the migration I think that is not problematic as it doesn't change the content only the method that is used.

Fix deprecation warnings from Nextcloud.

---

docs/clients.md

File to be updated: https://github.com/nextcloud/news/blob/master/docs/clients.md
App name: Communique
Description: RSS Reader with cross-platform sync
OS support: Linux (Flatpak)
Download Link: https://flathub.org/apps/details/com.github.suzie97.communique
Support Link: https://github.com/flathub/com.github.suzie97.communique
Sources: https://github.com/Suzie97/Communique
Signed-off-by: Anderson Silva <UnderEu@users.noreply.github.com>

Documentation: Add Communique app client

---

CHANGELOG.md
lib/Db/ItemMapperV2.php
tests/Unit/Db/ItemMapperTest.php

This doesn't fix all issues of the readAll function but makes it more predictable.
If you have a huge amount of unread feeds this function might still fail.

Fix when marking all items as read, all items of the user are used in the sql query

---

CHANGELOG.md
appinfo/info.xml

Changed
- Ported the admin settings to vue (#2353)
Fixed
- Fix PHP 8.1 deprecations (#1861)
- Document api item types (#1861)
- Fix deprecation warnings from Nextcloud server (#1869)
- Fix when marking all items as read, all items of the user are used in the sql query (#1873)
- Fix adding feed via the web-ui that was just deleted causing an error (#1872)

Release 18.2.0-beta1

---

lib/Db/ItemMapperV2.php
tests/Unit/Db/ItemMapperTest.php

We overlooked that the parameter "unread" is actually needed in the update statement.
I also changed the first query to simplify the code.

fix readAll method fails due to missing parameter

---

src/components/AdminSettings.vue

Apparently Transifex doesn't support the newer template literals syntax with backticks.
fixes #1893

fix truncated string for Transifex

---

CHANGELOG.md
js/controller/ContentController.js

The items returned by the backend is already sorted with the user's preferred order, so the first item should be just the first item of the returned list.
Should fix https://github.com/nextcloud/news/issues/1838

Fix the highlighted item in reversed order

---

.editorconfig
.eslintrc.js
babel.config.js
lib/Explore/feeds/feeds.en.json
src/App.vue
src/components/AddFeed.vue
src/components/Explore.vue
src/components/Sidebar.vue
src/main.js
stylelint.config.js
webpack.js

PR to Cleanup Linting rules + Use Typescript in all Components so far
-----
- follows https://github.com/nextcloud/news/pull/1831
- indentation: use tabs rather than spaces
- verify indentation in vue html templates
- remove `node/no-unpublished-import` rule because no more vue-property-decorator library
- no linting errors 
you can see the dev work done here
- https://github.com/devlinjunker/news/pull/33
Up Next:
-----
- Components to Typescript PR
- Add Unit Tests to run with npm run test
- Add Vuex Store (see https://github.com/nextcloud/news/commit/58a196b548e8bf25896ee7db159dbecf88724635 for preview)
- Add Proper Routing (see https://github.com/devlinjunker/news/compare/vue-version...devlinjunker:vue-routes for preview)

[Vue Rewrite] Clean up indentation + linting rules

---

src/App.vue
src/components/AddFeed.vue
src/components/Explore.vue
src/components/Sidebar.vue
src/shims-vue.d.ts
src/types/ExploreSite.vue
src/types/Feed.vue
src/types/Folder.vue

PR for Making all Component files use Typescript
----
Moved out of https://github.com/nextcloud/news/pull/1907 
(File changes in this PR contains the updates from #1907 until it is merged)
[Commits with actual changes](https://github.com/nextcloud/news/pull/1922/files/7ad99102534e48789ccc811dba001dc78c1a2202..2709767e2de83d353688a0ab3f9780d2627a95b5):
- a1b0d5878ad3ee287a7e9f368d67fd914d9eca86
- 2709767e2de83d353688a0ab3f9780d2627a95b5
- Move all components use `Vue.extend({ ... `
- Add `types/` directory with `.vue` files containing type definitions used throughout app
- Add Unit Tests to run with npm run test (see https://github.com/devlinjunker/news/pull/56 for WIP)
- Add Vuex Store (see https://github.com/nextcloud/news/commit/58a196b548e8bf25896ee7db159dbecf88724635 for preview)
- …

[Vue Rewrite] Move Component Files to Typescript

---

.github/workflows/api-integration-tests.yml
Makefile
docs/developer.md

I wrote down some documentation on how to run the integration tests to make it a bit easier for new people.
Also added the missing kill command to the workflow.

Add some documentation about the integration tests

---

src/components/AdminSettings.vue

Any Ideas how to explain how explain how the number of autoPurgeCount is applied when purgeUnread is enabled.
I think that it is not obvious enough.
In the docs we have this https://nextcloud.github.io/news/faq/#database-table-grows-too-big

fix wording to articles

---

Makefile

This allows  easier local building of the release, if you own the key and cert (which is only me)

add conditon to check for existing key and crt

---

.github/workflows/api-integration-tests.yml
.github/workflows/api-php-static-code-check.yml
.github/workflows/api-php-tests.yml
.github/workflows/build-release.yml
.github/workflows/post-merge-tasks.yml
CHANGELOG.md
appinfo/info.xml

- Drop support for Nextcloud 22, NC 22 has reached it's end of life.
- Add support for Nextcloud 25 
- Corrected article compact title bar position in NC25 (#1944)
- Fixed "Mark read through scrolling" in NC25 and NC24 (#1944)

Release 19.0.0-beta1

---

CHANGELOG.md
js/app/Config.js
js/directive/NewsScroll.js
js/gui/KeyboardShortcuts.js
lib/Controller/PageController.php
templates/part.content.warnings.php

Keyboard navigation through items was not working correctly in NC25 and highlighting active item  on scroll was not working in NC25, NC24, NC23 (I think) so I have attempted to fix this.
The cronjob warning notification layout was messed up on NC25 as well so also attempted a quick fix for that.
Also tidied up the version number stuff a bit. I feel like the Nextcloud JS globals (the `window.OC` object) should have that info but I couldn't find it anywhere 🤷. Dumping the version number from PHP into a data attribute feels wrong 🤠

Fix keyboard navigation + cron job notification

---

CHANGELOG.md
css/navigation.css

Fix the doubled/nested scroll bars in the navigation menu. Easy to reproduce if you have a couple of folders and open the settings menu. 
https://github.com/nextcloud/news/issues/411
Tested in Firefox and Edge.

Fix nested scroll bars in navigation

---

.github/workflows/api-integration-tests.yml
tests/api/feeds.bats
tests/api/folders.bats
tests/api/helpers/settings.bash
tests/api/items.bats
tests/test_helper/feeds/Nextcloud.rss
tests/test_helper/feeds/heise.xml

The app password is nice in local testing, since Nextcloud logs too much data if you use the user password. Setup_file and teardown_file are only executed once instead of running before and after every job.

Use app password, change setup method

---

package-lock.json
package.json
src/components/AdminSettings.vue
src/main-admin.js
tests/javascript/unit/components/AdminSettings.spec.ts
tests/javascript/unit/components/Explore.spec.ts

Related to https://github.com/nextcloud/news/pull/748
Follows #1982
- Plus a little bit of cleanup found while testing
- Verified that App Builds with `make`
- Verified that Admin Settings Page Loads on localhost (NC 25)
- Verified that App loads on localhost (NC 25)
- Verified that Jest Unit Tests Pass
- Add Vuex Store (see https://github.com/nextcloud/news/commit/58a196b548e8bf25896ee7db159dbecf88724635 for preview)
- Add Proper Routing (see https://github.com/devlinjunker/news/compare/vue-version...devlinjunker:vue-routes for preview)
- More UI Components to match current features!
- Eventually... Clean up old code

[Vue Rewrite] Add Unit Tests for Admin Settings

---

CHANGELOG.md
appinfo/info.xml
composer.json
composer.lock

Drop support for PHP 7.3

---

CHANGELOG.md

Changed
- Drop support for PHP 7.3 (#2008)
- Dependency updates
Basically 19.0.1 but this time without the php version mismatch

Release 20.0.0

---

src/App.vue
src/components/Sidebar.vue
src/components/Starred.vue
src/main.js
src/routes/index.js
src/routes/index.ts

Related to https://github.com/nextcloud/news/pull/748
Follows #2010
- Add separate file for Routing Config
- Add New Route and `StarredPanel` Component
- Verified that App Builds with `make`
- Verified that Admin Settings Page Loads on localhost (NC 25)
- Verified that App loads on localhost (NC 25)
- Verified that Jest Unit Tests Pass (`npm run test`)
- Verified that linting passes (`npm run lint/stylelint`) 
- Verified that New Route can be loaded
- TBD: Template Testing??
- WIP at https://github.com/devlinjunker/news/compare/vuex-store...devlinjunker:vue-template-tests
- TBH I'm not really sure this is worth it... I have looked at other nextcloud repos and do not see this in-depth of testing
- Look into Three Panel Layout ([Bookmarks …

[Vue Rewrite] Start More Routes

---

CHANGELOG.md
lib/Scraper/Scraper.php

The league/uri version that we inherit in Nextcloud is a bit outdated. That version can't handle certain uris.
Example log output:
```
{"reqId":"1b1RWb0wI5WE9YePk6DC","level":3,"time":"2023-01-10T12:48:17+00:00","remoteAddr":"","user":"--","app":"news","method":"","url":"--","message":"Unable to parse content from https://matrix.org/blog/2022/11/25/this-week-in-matrix-2022-11-25","userAgent":"--","version":"25.0.0.18","data":{"app":"news"}}
{"reqId":"1b1RWb0wI5WE9YePk6DC","level":0,"time":"2023-01-10T12:48:17+00:00","remoteAddr":"","user":"--","app":"news","method":"","url":"--","message":"Error during parsing of https://matrix.org/blog/2022/11/25/this-week-in-matrix-2022-11-25 ran into {\"class\":\"League\\Uri\\Exceptions\\SyntaxError\",\"message\":\"The uri `@yan:datanauten.de` contains …
```

Workaround for #2048

---

CHANGELOG.md
appinfo/info.xml

Fixed
- SyntaxError triggered when full-text is enabled with some items. (#2048, #2053)

Release 20.0.1

---

CHANGELOG.md
js/gui/KeyboardShortcuts.js

Previously when pressing the `O` key on article list, the handler for that keypress first simulated a click on that event in order to mark it as read, and only then opened the website that item links to in another tab. When having a lot of items on screen this caused a huge delay between pressing `O` and opening the linked article in a new tab. The delay was sometimes 5, even 10 whole seconds. This simple fix makes it so the article opens first, and then the click simulation happens afterwards.

Make the "open" keyboard shortcut work faster

---

CHANGELOG.md
lib/Fetcher/FeedFetcher.php

* Resolves: #2054
This is an alternate solution since I believe the core issue is empty URLs being sent to the favicon library.

fix: do not request favicon for empty base URL

---

CHANGELOG.md
lib/AppInfo/Application.php
lib/Search/FeedSearchProvider.php
lib/Search/FolderSearchProvider.php
lib/Search/ItemSearchProvider.php
tests/Unit/Search/FeedSearchProviderTest.php
tests/Unit/Search/ItemSearchProviderTest.php

I was motivated to look into article search.
Current implementation works as is but has potential for improvement.
Pagination should be used since there might be a lot of items that requires adjustments to the DB layer.
https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/search.html#pagination
As far as I could see and know we do not have a view for a single item, therefore there is no link to go to that item within news. Implementing that on the current frontend seems to me like it's not worth the effort.
For now I put the url to the external website for that item/article in there.
If we don't want this we could link to the feed, which would at least identify in which feed the information is found.

implement item/article search

---

CHANGELOG.md
appinfo/info.xml

Release Notes:
Changed
- Drop support for Nextcloud 23 (#2077 )
- Make the "open" keyboard shortcut work faster (#2080)
- Implemented search for articles, results can only link to the feed. (#2075)
Fixed
- Stop errors from the favicon library over empty values (#2096)

Release 21.0.0-beta1

---

CHANGELOG.md
appinfo/info.xml
docs/faq.md
lib/Migration/RemoveUnusedJob.php
mkdocs.yml

Long time ago we changed the job name for our background job.
That left the old job in the db of many installations it also confuses some people when one job gets stuck.
This repair step which is run after the upgrade of the app or anytime the repair steps are triggered from occ, removes the job.
Example output, tested on dev environment.
```
...
- Set existing shares as accepted
- Remove the unused News update job
- Job exists, attempting to remove
- Job removed
- Update OAuth token expiration times
...
- Set existing shares as accepted
- Remove the unused News update job
- Job does not exist, all good
- Update OAuth token expiration times
- Initialize migration of background images 
...
```
- Code is [properly formatted](https://nextcloud.github.io/news/developer/#coding-style-guidelines …

Chore remove unused News job

---

.github/workflows/api-integration-tests.yml
.github/workflows/api-php-static-code-check.yml
.github/workflows/api-php-tests.yml
.github/workflows/build-release.yml
.github/workflows/post-merge-tasks.yml

Updates the CI to use stable26.

use stable26

---

CHANGELOG.md
lib/Service/StatusService.php
lib/Settings/AdminSettings.php
package-lock.json
package.json
src/components/AdminSettings.vue
tests/Unit/Service/StatusServiceTest.php

Display  a info card in the settings, indicating when the last news update job ran.

add cron status badge to admin setting

---

lib/Fetcher/FeedFetcher.php

* Resolves: # n/a
Currently the user agent is hardcoded in multiple places, it makes sense to have it in one place instead.
We could also consider to provide the version of Nextcloud news in the useragent instead of the fixed 1.0

store useragent in one place

---

CHANGELOG.md
appinfo/info.xml
lib/Fetcher/FeedFetcher.php
lib/Fetcher/Fetcher.php
lib/Fetcher/IFeedFetcher.php
lib/Service/FeedServiceV2.php
tests/Unit/Fetcher/FeedFetcherTest.php

* Resolves: #2118  
Hand httpLastModified database field to FeedIo for setting If-Modified-Since header

Use httpLastModified field for If-Modified-Since header on feed updates

---

CHANGELOG.md
lib/Db/ItemMapperV2.php
tests/Unit/Db/ItemMapperTest.php
tests/api/items.bats

if this is not updated the API won't work correctly and we get sync errors.
* Resolves: https://github.com/nextcloud/news-android/issues/1105 https://github.com/nextcloud/news-android/issues/1117
Mark feeds on the server as read - timestamp not updated
If android app already had the item it won't see a change
-> items on android still marked as unread

Fix: set lastmodified in items->readAll

---

CHANGELOG.md
appinfo/info.xml

Fixed
- Fix last_modified not updated when all items are marked as read (#2183)

Release 21.2.0-beta2

---

tests/command/feeds.bats
tests/test_helper/feeds/Nextcloud.rss
tests/test_helper/feeds/heise.xml
tests/test_helper/feeds/no_guid_feed.xml
tests/updater/update.bats

* Resolves: Tests Failing
fix ?? operator, I'm not sure what ??= does but apparently not what we wanted. ?? is evaluating if the expression to the left is null and assigns the default value on the right.
"null coalescing" operator
https://www.php.net/manual/en/language.operators.comparison.php#language.operators.comparison.coalesce

fix integration tests

---

CHANGELOG.md
css/content.css
templates/index.php

* Resolves: #2192 
Add CSS class `nc-major-version-gte-25` to `div#app-content` when NC major version is >= 25 to fix this issue for all upcoming NC versions.

Fix display issue in NC26+ (#2192)

---

CHANGELOG.md
lib/Db/ItemMapperV2.php
tests/Unit/Db/ItemMapperTest.php

This is a quick-fix to Improve a specific SQL query from 22-37s to  <1s when refreshing news items.
Some details how I got to that solution:
Activate slow-queries
```sql
SET GLOBAL slow_query_log=1;
```
Revealed slow-query:
```sql
SELECT `items`.* FROM `oc_news_items` `items` INNER JOIN `oc_news_feeds` `feeds` ON items.feed_id = feeds.id WHERE feeds.user_id = 'xxx' ORDER BY `items`.`id` DESC LIMIT 1;
// 1 row in set (37.087 sec)
SELECT count(*) from oc_news_items;
// 156391
```
After reducing payload (`items.*` --> `items.id`) the query is way faster:
```sql
SELECT `items`.`id` FROM `oc_news_items` `items` INNER JOIN `oc_news_feeds` `feeds` ON items.feed_id = feeds.id WHERE feeds.user_id = 'xxx' ORDER BY `items`.`id` DESC LIMIT 1;
// 1 row in set (0.042 sec)
```
`newest()` now only …

Improve sql query performance by removing unused payload

---

CHANGELOG.md
templates/part.navigation.addfeed.php

* Resolves: #2090
Fixed sorting of folder names in select when adding subscription.
Using the same orderBy filter as for the folder list below to get the same order.

Fix sorting of folder names in select when adding subscription

---

CHANGELOG.md
css/content.css
js/directive/NewsStickyMenu.js

* Resolves: #2142
Fix audio player floating when scrolling in NC25+.
Using the #app-content.nc-major-version-gte-25 class introduced in #2196 in CSS and  the NC_MAJOR_VERSION constant in JavaScript to apply (and limit) changes to NC versions >= 25.
Currently there are no changes regarding the overlapping navigation toggle icon on screens < 1024 pixels width as the expected behavior should be discussed before.

Fix audio player floating when scrolling

---

CHANGELOG.md
lib/Controller/PageController.php

* Resolves: Nothing
* 
related to #2242
Removes the error message of the browser but buttons still don't work.

allowEvalScript set to true

---

CHANGELOG.md
lib/Config/FetcherConfig.php

As long as we use Feed-io < 6, we always use Guzzle (with Feed-io 6, we need to choose a [HTTPlug](https://httplug.io/) library ourselves). Guzzle [supports](https://docs.guzzlephp.org/en/stable/request-options.html#decode-content) transparently decompressing gzip or deflate compressed responses, which is enabled by default.
Feed-io does this [by default](https://github.com/alexdebril/feed-io/pull/311/commits/ffef9eaabefcfc66bca3bb598b952d13842f14b5), but as we override the headers, we have to add a fitting `Accept-Encoding` header as well.
Previously, my feed collection caused up to 45.9 MB download traffic per cronjob, with this commit it is as low as 23.6 MB.
- [Sign-off …

Use HTTP compression for downloads

---

docs/install.md

-fix "then" vs "than"
-standardize capitalization of "News"
* Resolves: # 

install.md minor grammar changes

---

.github/workflows/api-integration-tests.yml
.github/workflows/api-php-static-code-check.yml
CHANGELOG.md
appinfo/info.xml
docs/install.md

* Resolves: # 
Drop support for PHP 7.4 new min. version is php 8.0

Drop support for PHP 7.4 new min. version is php 8.0

---

CHANGELOG.md
composer.json
composer.lock
lib/Fetcher/Client/FeedIoClient.php
lib/Fetcher/FeedFetcher.php
tests/updater/update.bats

* Resolves: # 
Upgrade feed-io to v5.1.3
Should fix the bug that items with the latest version are ignored. #2236

Upgrade feed-io to v5.1.3

---

CHANGELOG.md
appinfo/info.xml

One step forward in modernizing news, we have to drop PHP 7.4 since our main library feed-io does not support 7.4 in newer versions. News users will benefit from the improvements in the library, fewer issues when adding, updating feeds.
This will be not the last step. The next major feed-io version doesn't support PHP 8.0 so when we upgrade to that we will also drop support for PHP 8.0 and 8.1 will be the minimum.
Changed
- Drop support for PHP 7.4 new min. version is php 8.0 (#2237)
- Upgrade feed-io to v5.1.3 (#2238)

Release 23.0.0-beta1

---

.github/workflows/post-merge-tasks.yml

fix codecoverage never executed

fix codecoverage never executed

---

CHANGELOG.md
appinfo/info.xml

* Resolves: #2236
Changed
- Drop support for PHP 7.4 new min. version is php 8.0 (#2237)
- Upgrade feed-io to v5.1.3 (#2238)
Fixed
- Some feeds missing items (#2236)

Release 23.0.0

---

.github/workflows/api-integration-tests.yml
.github/workflows/api-php-tests.yml
CHANGELOG.md
appinfo/info.xml
lib/Service/StatusService.php

* Resolves: # 
Drop support for Nextcloud 25

drop support for Nextcloud 25

---

CHANGELOG.md
appinfo/info.xml
docs/troubleshooting.md
lib/Command/Updater/Job.php
lib/Service/UpdaterService.php
tests/Unit/Service/UpdaterTest.php
tests/command/update.bats

This is also a Feature that requires Nextcloud 26
This adds a new command `news:updater:job` that allows to check on the current status of the background job and also allows to reset the job.
Resetting may lead to issues if the job is currently running but is certainly better than modifying the DB directly.
I also updated the FAQ a bit and moved the old steps into their own section. I think they can be removed in the future.
This is part of the effort to improve the job situation in news, which is one of the main error sources and reason why people open an issue.
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all …

Add a command to check the job status and reset it

---

CHANGELOG.md
lib/Config/FetcherConfig.php
lib/Fetcher/FeedFetcher.php
tests/Unit/Fetcher/FeedFetcherTest.php

* Resolves: #2326
Check the available compression types

Check available compression types of curl

---

CHANGELOG.md
docs/install.md
docs/troubleshooting.md
lib/AppInfo/Application.php
lib/Fetcher/FeedFetcher.php
lib/Utility/Cache.php
tests/Unit/Fetcher/FeedFetcherTest.php

* Resolves: #2325 
We had multiple reports now of shared hoster environments where the updating of some feeds fail because they can't write to the temp directory.
One possible issue is that they can't write to /tmp at all (which is the default nextcloud uses).
Or that they can write to /tmp but for some reason the hoster allows all users to share /tmp.
This PR changes that in using the instance ID of Nextcloud a unique identifier that is stable.
Example from my dev instance:
```
root@31fa29494eed:/var/www/html# ls -l /tmp/news-oc2iqvwq927d/cache/
total 12
drwxr-x--- 2 www-data www-data 4096 Aug 22 16:50 feedFavicon
drwxr-x--- 2 www-data www-data 4096 Aug 22 16:42 feedLogo
drwxr-x--- 4 www-data www-data 4096 Aug 22 16:42 purifier
```
- Code is [properly …

use unique name for cache folder

---

CHANGELOG.md
appinfo/info.xml

Changed
- Drop support for Nextcloud 25, Supported: 26, 27 (#2316)
- Add a new command for occ `./occ news:updater:job` allows to check and reset the update job (#2166)
- Check for available http(s) compression options and use them (gzip, deflate, brotli) (#2328)
- Change and unify [cache](https://nextcloud.github.io/news/install/#cache) to use the instance ID of Nextcloud (#2331)

Release 24.0.0-beta1

---

src/App.vue
src/components/Sidebar.vue
src/components/feed-display/FeedItemDisplay.vue
src/components/feed-display/FeedItemDisplayList.vue
src/components/routes/All.vue
src/components/routes/Folder.vue
src/components/routes/Starred.vue
src/components/routes/Unread.vue
src/dataservices/item.service.ts
src/routes/index.ts
src/store/item.ts
tests/javascript/unit/components/routes/All.spec.ts
tests/javascript/unit/components/routes/Folder.spec.ts
tests/javascript/unit/services/item.service.spec.ts
tests/javascript/unit/store/item.spec.ts

Related to https://github.com/nextcloud/news/pull/748
Follows https://github.com/nextcloud/news/pull/2343
Add Route + Components for:
- All Articles in Folder
- All Articles in DB
Add More Material Design Icon Components to Side Panel
~- [ ] Changelog entry added for all important changes.~ (Can we add the `skip-changelog` label to prevent the check for changelog? )
All Articles Route:
Folder Articles Route:
Side Bar Icons:
- Sidebar Actions ([WIP](https://github.com/devlinjunker/news/commit/7e9f96947c40a2088f1d88ead901ecee46933a93))
- use `?selected=<id>` url query parameter to store and parse which Feed Item is displayed in `FeedItemDisplay`
- Update Documentation
- Mobile friendly layout
- Warning and Error Messages
- Audio/Video Feed Items
- Share Menu
- Clean up Explore Panel
- Quick …

[Vue Rewrite] Routes: Folder and All Articles Components and Routes

---

.github/workflows/build-release.yml

The version that was used is already 3 years old and running with an old node version :)

update php setup action

---

lib/Fetcher/FeedFetcher.php

Log more useful things when checking the logo

Log more useful things when checking a logo

---

lib/Explore/feeds/feeds.en.json
src/components/AddFeed.vue
src/components/routes/Explore.vue

Related to https://github.com/nextcloud/news/pull/748
- Copy styles from old `explore.scss` file to Vue File
- Use flex to make grid more responsive
- Clicking subscribe button opens `AddFeed` popover with url pre-populated from feeds.en.json request data
~- [ ] Changelog entry added for all important changes.~
Using FlexGrid CSS
Clicking Subscribe Button
- Update Documentation for Front End
- Developer 
- Frontend Tips/Organization
- Front End Unit Tests
- Sharing
- Remove Frontend/JS Plugin Documentation ( should we just update this when we add the new `addArticleAction` Plugin API?)
- Settings in Sidebar
- Component
- Backend Requests + Application Behavior Changes
- Keyboard Navigation
- Mark on Scroll
- Reverse Order (Oldest to Newest)
- Upload/Download Subscriptions/Articles
- use …

[Vue Rewrite] Explore Page styles and behavior

---

CHANGELOG.md
lib/Scraper/Scraper.php

Some sites do not serve content without a User Agent 
Set CURLOPT_USERAGENT= FetcherConfig::DEFAULT_USER_AGENT

Fix: Set CURLOPT_USERAGENT for Scraper

---

CHANGELOG.md

- Major Rewrite of the Frontend with Vue JS (#748) For comments and suggestions for the new UI, please use this: https://github.com/nextcloud/news/discussions/2388
- Set User Agent for curl in Scraper (#2380)
- Drop support for Nextcloud 26, Supported 27

Release 25.0.0-alpha1

---

.github/workflows/api-integration-tests.yml
.github/workflows/api-php-static-code-check.yml
.github/workflows/api-php-tests.yml

Don't build frontend code to save CI time when only running PHP tests

---

CHANGELOG.md
lib/Search/FeedSearchProvider.php
lib/Search/FolderSearchProvider.php
lib/Search/ItemSearchProvider.php
tests/Unit/Search/FeedSearchProviderTest.php
tests/Unit/Search/FolderSearchProviderTest.php
tests/Unit/Search/ItemSearchProviderTest.php

* Resolves: #2408
The routes for feeds and folders changed during the Vue rewrite.

Adjust search urls to match changed Vue routes

---

CHANGELOG.md
package-lock.json
package.json
src/App.vue
src/components/ContentTemplate.vue
src/components/feed-display/FeedItemDisplay.vue
src/components/feed-display/FeedItemDisplayList.vue
src/components/feed-display/FeedItemRow.vue
src/components/routes/All.vue
src/components/routes/Explore.vue
src/components/routes/Feed.vue
src/components/routes/Folder.vue
src/components/routes/Starred.vue
src/components/routes/Unread.vue
tests/javascript/unit/components/routes/All.spec.ts
tests/javascript/unit/components/routes/Feed.spec.ts
tests/javascript/unit/components/routes/Folder.spec.ts
tests/javascript/unit/components/routes/Starred.spec.ts
tests/javascript/unit/components/routes/Unread.spec.ts

I made some improvements to the new vue frontend:
- use Nextcloud components for item list & article view
- behaves better on small/narrow screens

Vue improvements

---

CHANGELOG.md
lib/Search/FeedSearchProvider.php
lib/Search/FolderSearchProvider.php
lib/Search/ItemSearchProvider.php

Adjusts search to use filters rather than terms, fixing the phpstan check

fix: adopt search to NC 28 filters

---

tests/Unit/Utility/TimeTest.php
tests/command/feeds.bats

* Resolves: # 
This should hopefully fix the time test.
The time test fails sometimes on our ci probably because php is simply to fast or does some magic.

Fix Time Test failing for no reason

---

lib/Explore/feeds/feeds.en.json

The CCMixter favicon was responsible for browsers emitting a mixed content warning when running Nextcloud behind an SSL certificate. While at it, I changed all other http URLs to https, ensuring that all those URLs are also still working with https.

use https for all explore feed urls and favicons

---

CHANGELOG.md
appinfo/info.xml
docs/install.md
lib/AppInfo/Application.php
lib/Listeners/AddMissingIndicesListener.php
lib/Migration/Version140200Date20200824201413.php
lib/Migration/Version150004Date20201009183830.php
lib/Migration/Version150005Date20201009192341.php

* Resolves: #2526
This should in theory allow admins to get the notification of missing indices and the option to add them via
`occ db:add-missing-indices`
tested:
```
root@5a630161f41e:/var/www/html# sudo -u www-data php ./occ db:add-missing-indices          
Adding additional news_feeds_deleted_at_index index to the oc_news_feeds table, this can take some time...
oc_news_feeds table updated successfully.
```

Add Listener for missing db indices

---

src/components/AdminSettings.vue
src/components/ContentTemplate.vue
src/components/ShareItem.vue
src/components/feed-display/FeedItemDisplay.vue
src/components/feed-display/FeedItemRow.vue
src/dataservices/feed.service.ts
src/dataservices/folder.service.ts
src/main.js
src/store/item.ts

* Resolves: # 
Fixes annoying errors in each PR

fix: ESLint errors

---

CHANGELOG.md

Changed
- Add DB index for news_feeds.deleted_at (#2526)
Fixed
- PostgreSQL implement fix for marking over 65535 unread items as "read" (#2557)

Release 25.0.0-alpha4

---

CHANGELOG.md
lib/Controller/ExportController.php

* Resolves: #2601  
Fix deprecated variable reference

Fix deprecated variable reference

---

src/components/feed-display/FeedItemRow.vue

This small change fixes that feed item rows are not growing horizontally when the title and description are very short.

Fix horizontal grow of feed item rows

---

CHANGELOG.md
appinfo/info.xml

Changed
- make occ news:updater:job exit with code 2 if last update was too long ago (#2590)
- Fix deprecated variable reference in ExportController.php (#2602)
- Add support for Nextcloud 29 (#2611)

Release 25.0.0-alpha5

---

CHANGELOG.md
package-lock.json
package.json
src/components/feed-display/FeedItemDisplayList.vue
src/main.js

Implements parts of #2480 and serves as basis for other keyboard shortcuts.
WORK IN PROGRESS!

Keyboard navigation

---

CHANGELOG.md
src/components/feed-display/FeedItemDisplayList.vue

* Resolves: https://github.com/nextcloud/news/pull/2671#issuecomment-2164692280
- fix undefined item when using `j` and `k` keyboards shortcuts in an empty feed

fix: undefined item when using j/k akeyboards shortcuts in empty feed

---

lib/Service/FeedServiceV2.php

* Resolves: no issue
When feedIo cannot match any parser (rss, atom, ..) to the feed it will throw NoAccurateParserException.
So far our code does not handle this exception instead the exception is logged by nextcloud.
It is more useful to know which url triggered this.
Throwing a ReadErrorException because that is how we track feed fetching errors in the service.

log warning if feed cannot be parsed

---

CHANGELOG.md
src/components/feed-display/FeedItemDisplayList.vue

Persist the filter state and show unread items by default.

add: filter persistence

---

CHANGELOG.md
appinfo/info.xml

* Resolves: # 
Changed
- Add support for moving feeds to another folder from the sidebar feed menu (#2707)
- Persist the filter state and show unread items by default (#2704)
Fixed
- Fix undefined item when using `j` and `k` keyboards shortcuts in an empty feed (#2689)

Release 25.0.0-alpha8

---

CHANGELOG.md
lib/Migration/Version250000Date20240817095614.php

* Resolves: #2692
Allow feed title to be null in DB. Nothing we can do in the backend when there is no title.

Add migration to allow feed title to be null

---

docs/api/api-v2.md
lib/Config/FetcherConfig.php
lib/Scraper/IScraper.php
lib/Utility/Time.php
src/components/AdminSettings.vue
src/dataservices/item.service.ts
tests/api/feeds.bats

fix: resolve typos

---

.devcontainer/devcontainer.json
.devcontainer/setup.sh

* Resolves: # 
Shamelessly copied from https://github.com/nextcloud/deck/tree/main/.devcontainer, let's give this a try

feat: add devcontainer for development

---

src/App.vue

fix: remove styles for `.material-design-icon` which act on top navbar

---

CHANGELOG.md
lib/Fetcher/FeedFetcher.php

This addresses a scenario where a server providing a feed responds with a `Last-Modified` header that is derived from a file modification time. A static site generator, for example, may re-create a feed file without making changes to the file contents - in particular the `pubDate` for any feed items. Now the mtime and `Last-Modified` header have a date that is newer than any `pubDate` elements.
If News sends a request with a `If-Modified-Since` header based on the older `pubDate` then the server will respond with 200 and send the entire feed file contents even though the feed has not logically changed. To minimise server bandwidth, ideally News sends a last modified date based on the `Last-Modified` header it received during the last fetch so that the server can respond with 304.
- When …

fix: store HTTP last modified date from response header

---

src/components/feed-display/FeedItemDisplayList.vue
src/components/feed-display/VirtualScroll.vue

feed-item-row height is actual 110.66px, but setting this fixed is not optimal and should be changed in the future.
related: #2498 #2677
The scrolling was prepared in #2677, but not active. This activate scrolling and fixed the bumping.

fix: scrolling when using keyboard navigation

---

CHANGELOG.md
src/components/AdminSettings.vue

* Resolves: # #2533
This fixes the TypeError when changing admin settings.
```
TypeError: this.$refs.field is undefined
mounted index.mjs:35
VueJS 9
js</<.on["update:checked"]< AdminSettings.vue:1
```

fix: set correct classes for settings and setting hints

---

tests/Unit/Fetcher/FeedFetcherTest.php

* Resolves: Failing unit tests from #2724 
When creating a `Feed` instance, `httpLastModified` should be null until the fetcher retrieves a correct value from the feed server.

fix(tests): initialise http last modified as null

---

CHANGELOG.md
lib/AppInfo/Application.php
lib/Config/FetcherConfig.php
lib/Fetcher/FaviconDataAccess.php
lib/Fetcher/FeedFetcher.php
tests/Unit/Config/FetcherConfigTest.php

Updates the user agent to include the current application version. Will help feed hosts to determine whether a user is running the latest version of the news app when troubleshooting issues.

fix: use updated user agent when fetching feeds and favicons

---

CHANGELOG.md
appinfo/info.xml

* Resolves: # 
Fixed
- Use updated user agent when fetching feeds and favicons (#2788)
- Allow feed title to be null in DB. (#2745)
- Store HTTP last modified date from response header (#2724)
- Admin settings could not be saved (#2533)

Release 25.0.0-alpha9

---

CHANGELOG.md
appinfo/info.xml

* Resolves: #2719
- Require NC 29 or 30, dropped support for NC 28
- Require PHP 8.2 or higher
- Scroll position is not reset when switching between articles & feeds (#2548)
- Unread counter does not count down when folders or feeds are marked read (#2800)
- Query fetching status didn't work (#2800)
- Keyboard shortcuts are active even when searching (#2738)

Release 25.0.0-alpha10

---

CHANGELOG.md
lib/AppInfo/Application.php
lib/Controller/PageController.php
lib/Listeners/UserSettingsListener.php
package.json
src/components/Sidebar.vue
src/components/feed-display/FeedItemDisplayList.vue
src/components/modals/HelpModal.vue
src/dataservices/item.service.ts
src/store/app.ts
src/store/feed.ts
src/store/item.ts
tests/Unit/Controller/PageControllerTest.php

* Related: #2503 #2678 #2626
Things that are still missing here:
- mark as read on scroll feature is not yet implemented
- import/export feeds and articles

fix: add user settings

---

CHANGELOG.md
src/components/feed-display/FeedItemDisplayList.vue
src/components/routes/Unread.vue
tests/javascript/unit/components/feed-display/FeedItemDisplayList.spec.ts

* Resolves: #2516 
other fixes:
- when article marked read they are deleted from the unread item list and therefor the unread list is never greater than the cache.
- marked read items disappear when showAll is disabled in folder or feed view

fix: Feed item lists are merged when filtered 

---

src/components/feed-display/FeedItemDisplayList.vue

* Related: ef695d32a2fea81b299de166c63675858a3ff57c
I have not added a changelog entry, as it is only a small change to a recent commit

fix: read starred items not shown when showAll is disabled

---

CHANGELOG.md
src/components/feed-display/VirtualScroll.vue

* Related: #2503
The last items at the end are not marked read, because  they do not scrolled out. This will be another task to scroll the last items out of the view as in news 24.

fix: Mark as read on Scroll

---

CHANGELOG.md
lib/Controller/PageController.php
src/App.vue
src/routes/index.ts
src/store/app.ts

* Resolves: #2507
Open news with the last viewed feed or folder
The state of the folders is stored in an other table, so this will be an other task to do.

fix: Navigating to the news app always opens /explore instead of remembering the last viewed feed

---

CHANGELOG.md
src/components/feed-display/VirtualScroll.vue

* Related: #2817
Add ::after css from News 24 so that articles can be scrolled out and marked read as before

fix: restore old scroll behaviour to scoll after arcticles needed for mark scroll on read

---

CHANGELOG.md
docker/Makefile
src/components/feed-display/FeedItemDisplayList.vue
src/components/routes/Feed.vue
src/dataservices/item.service.ts
src/store/item.ts
term.kdl

* Resolves: #2678
This pull requests now implements the ordering of feed item in the item list.

ordering: implement in item list

---

lib/Controller/ApiController.php
lib/Controller/Controller.php
lib/Controller/ExportController.php
lib/Controller/FeedApiController.php
lib/Controller/FeedController.php
lib/Controller/FolderApiController.php
lib/Controller/FolderApiV2Controller.php
lib/Controller/FolderController.php
lib/Controller/ItemApiController.php
lib/Controller/ItemController.php
lib/Controller/PageController.php
lib/Controller/UtilityApiController.php
tests/command/feeds.bats
tests/command/items.bats

See https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/rest_apis.html

chore: use annotations for controllers

---

CHANGELOG.md
src/components/feed-display/FeedItemDisplayList.vue
tests/javascript/unit/components/feed-display/FeedItemDisplayList.spec.ts

* Resolves: #2833
Added a new filter to prevent items that were loaded in other views with eventually different orderings from popping up early in a merged view.
Add only Items to the view where item id are between start and the view specific lastItemLoaded.

fix: Items keep popping up in Folder, All or Unread view

---

CHANGELOG.md
src/components/Sidebar.vue
src/components/feed-display/FeedItemDisplayList.vue
src/components/feed-display/FeedItemRow.vue
src/components/routes/Feed.vue
src/dataservices/feed.service.ts
src/dataservices/item.service.ts
src/store/feed.ts
src/store/item.ts
tests/javascript/unit/components/feed-display/FeedItemRow.spec.ts

* Resolves: #2846
* Resolves: #2847
This PR changes the way when the sorted item list is updated, to prevent sorting the whole list for every click or twice for changing to next item when navigating with keyboard.
Also the item list now shows the correct items immediately after changing, the feed or global sort order.

Performance improvements and ordering rework

---

CHANGELOG.md
lib/Db/FeedMapperV2.php
lib/Db/FolderMapperV2.php

* Resolves: #2838
This is the simplest and most efficient way to get the sidebar items sorted, instead of adding another sort to the frontend sidebar logic.
But I don't know if there are other APPS that uses this API and expect the current order, which actually corresponds to the date of creation
The only disadvantage is that when new elements are added, they have to be resorted or the page must be reloaded.
@Grotax @SMillerDev 
If you agree, I will add the logic to re-sort the list when adding feeds or folders in a new PR.
- Changelog entry added for all important …

fix: Folders and Feeds in Sidebar are not sorted alphabetically

---

CHANGELOG.md
appinfo/info.xml

Changed
- Performance improvements on item list
- Rework feed and global sort ordering
- Add 'r' shortkey to refresh feed and item list
- Show automatically new news items on VueJS implementation (#2502)
- Show when feeds and folder have errors
- Add keyboard shortcuts 'd', 'f', 'c' and 'v' to switch between feeds and folders
Fixed
- starred items in a feed can prevent further scrolling
- j shortcut doesn't load more items in infinite scroll (#2847)
- Feed ordering uses wrong values (#2846)
- Folders and Feeds in Sidebar are not sorted alphabetically (#2838)
- Unread Counter becomes negative (#2839)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.m …

Release 25.0.0-alpha13

---

package-lock.json
package.json
src/components/AdminSettings.vue
src/components/ContentTemplate.vue
src/components/Sidebar.vue
src/components/SidebarFeedLinkActions.vue
tests/javascript/helpers/unist-stub.js
tests/javascript/unit/components/AdminSettings.spec.ts

Related: #2503
In preparation for alternative view modes like compact or hopefully the old non-compact mode an update to nextcloud-vue v8 is needed.
This enables the use of different layouts for [NcAppContent](https://nextcloud-vue-components.netlify.app/#/Components/App%20containers/NcAppContent?id=ncappcontent-1) (`vertical-`,` horizontal-` and `no-split`). 
`no-split` came with nextcloud-vue 8.10.0,` hoizontal-split` with 8.11.0.
The needed changes were straightforward (https://github.com/nextcloud-libraries/nextcloud-vue/issues/4223).
There are small visible changes:
**Light theme v7:**
**Light theme v8:**
**Dark theme v7:**
**Dark theme v8:**
The new library causes a problem with the unit-test (jest), which I bypassed with moduleNameMapper in package.json.
The problem seems that the …

update nextcloud-vue v8

---

CHANGELOG.md
lib/Db/Feed.php
lib/Service/FeedServiceV2.php

* Resolves: #2797
While testing the new opml import function and trying to export the feeds from my dev server as opml I came across this issue again, since #869 and  #2745 it is possible to add feeds without a title.
But this is causing other issues for example when you try to export your feeds because the DB Feed Entity expects the title to be a string.
With my changes it is now ok if a feed title is null, that should allow people to see feeds even when they do not have a title.
This is of course not optimal because a feed without a title is hard to identify in the feed list, if the feed has a logo or favicon you at least see that else you just see an empty line. You are still able to call open the menu though to remove or rename the feed.
So I also added a check if the title is null …

fix feed title issues

---

CHANGELOG.md
src/components/feed-display/FeedItemDisplay.vue
src/components/feed-display/FeedItemRow.vue
src/components/feed-display/VirtualScroll.vue
src/types/FeedItem.ts
tests/javascript/unit/components/feed-display/FeedItemRow.spec.ts

The temporary keep unread flag for items is now kept until leaving or reloading the news app.

fix: Keep Unread is now respected during mark read on scroll and is kept during feed/folder changes

---

package-lock.json

http-proxy-middleware  <2.0.7
Severity: high
Denial of service in http-proxy-middleware - https://github.com/advisories/GHSA-c7qv-q95q-8v27
ip  *
Severity: high
ip SSRF improper categorization in isPublic - https://github.com/advisories/GHSA-2p57-rm9w-gvfp
socks  1.0.0 - 2.7.1
Depends on vulnerable versions of ip
tar  <6.2.1
Severity: moderate
Denial of service while parsing a tar file due to lack of folders count validation - https://github.com/advisories/GHSA-f5x3-32g6-xq36

deps: fix npm audit

---

CHANGELOG.md
appinfo/routes.php
lib/Controller/ImportController.php

* References: #2541, #2874
This adds an API that will take an OPML file as either a File upload with the name `file`, or as a request body.

feat: Add OPML Import API

---

CHANGELOG.md
src/components/Sidebar.vue
src/store/folder.ts

* Related: #2541 
Add import/export to user settings. Keep as draft until the api "/import/opml" is implemented.

feat: add import/export opml to user settings

---

CHANGELOG.md
src/components/ContentTemplate.vue
src/components/MoveFeed.vue
src/components/Sidebar.vue
src/components/feed-display/FeedItemDisplayList.vue
src/components/routes/Starred.vue
src/components/routes/Unread.vue
src/store/feed.ts

Resolves: #2847 
These filters are redundant to the unread and starred route, but they only filter already loaded items and didn't will work as expected, because they could initially hide items or prevent the scroll from loading additional items from the backend, depending the user settings.
For an app that has only a small part of all items loaded, this type of filter cannot work.

Remove non-functional unread and starred filter and code cleaning

---

CHANGELOG.md
src/components/ContentTemplate.vue
src/components/Sidebar.vue
src/components/feed-display/FeedItemDisplay.vue
src/components/feed-display/FeedItemDisplayList.vue
src/components/feed-display/FeedItemRow.vue
src/components/feed-display/VirtualScroll.vue

* Resolves: #2505
* Related: #2503
This PR adds alternative modes configurable in the user settings and allow to move the feed list splitter to 100%.
* compact mode: If an article is clicked the article is shown using the whole content view.
* expanded compact mode: horizontal split mode with the item displayed below the item list
**Compact Mode Light Theme**
**Compact Mode Details Light Theme**
**Compact Mode Dark Theme**
**Compact Mode Details Dark Theme**
**Expanded Compact Mode Ligtht Theme**
**Expanded Compact Mode Dark Theme**
- Changelog entry added for all …

add single column layout (compact mode)

---

.github/workflows/build-release.yml

As mentioned by the docs nightly releases are meant for automated (nightly) builds, which we do not have, therefore changing the setting to false.
Also I want to change the format of the version for pre-releases by adding a dot.
25.0.0-alpha14 would become 25.0.0-alpha.14 both are valid semver versions but it seems like many nextcloud apps use the later format so I would like to adjust to that.
Fingers crossed that the appstore will actually understand that those are pre-releases.
https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/release_process.html#pre-releases
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) …

never tag a release as nightly in the appstore

---

CHANGELOG.md
src/components/AddFeed.vue
src/components/ContentTemplate.vue
src/components/Sidebar.vue
src/components/SidebarFeedLinkActions.vue
src/components/feed-display/FeedItemDisplayList.vue
src/components/routes/Feed.vue
src/components/routes/Folder.vue
src/dataservices/item.service.ts
tests/javascript/unit/components/Sidebar.spec.ts
tests/javascript/unit/components/feed-display/FeedItemDisplayList.spec.ts

* Resolves: #2903
* Resolves: #2900 
* Resolves: #2895 
This PR also fixes:
* don't add folder when already exist
* disable subscribe button and show loading icon during adding feed process
* don't show pinned feeds with no unread items when "Show all articles" is disabled
* add missing shortcut 'shift + a' to mark all articles in current feed/folder read

Set of fixes for 25.0.0

---

CHANGELOG.md
appinfo/info.xml

Changed
- always show `All articles` route entry (#2913)
- remove confirmation dialog when mark read folders/feeds (#2913)
- add shortcut 'shift + a' to mark all articles in current feed/folder read (#2913)
Fixed
- shortcut 'r' not working in unread view when "Show all articles" is enabled (#2913)

Release 25.0.1

---

CHANGELOG.md
appinfo/info.xml

Fixed
- add h1 header to title in feed item row for better accessibility (#2921)
- Downgrade htmlpurifier to 4.17.0 to fix log flooding (#2924)

Release 25.0.2

---

.github/workflows/frontend-nodejs-tests.yml

* Resolves: # 
While the frontend tests were running I checked the logs and was a bit surprised that `apt install firefox` caused a install of the snap version over the already installed firefox image. I guess that is what ubuntu is today... well. And setting up snap and installing it over the existing install of course takes for ever.
Therefore removing the install step that I added 4 years ago. December 5 Github will start switching the ubuntu-latest label to ubuntu 24.04 will see if that breaks something.

[Actions] Frontend tests do not try to install firefox

---

CHANGELOG.md
src/components/ContentTemplate.vue
src/components/feed-display/FeedItemDisplayList.vue
src/components/feed-display/FeedItemRow.vue
src/components/feed-display/VirtualScroll.vue

* Resolves: #2940 
* Related: #2919
* Related: #2920 
This PR adds fixes for screen readers
* add landmarks for the content list and details
* make article list recognized by screen readers
* item can be selected by screen readers during heading navigation

Screenreader fixes

---

CHANGELOG.md
src/components/Sidebar.vue

* Resolves: #2944 
* remove mime type check when importing `opml`, they are not reliable anyway

fix: remove mime type check when importing opml

---

CHANGELOG.md
lib/Controller/PageController.php
src/components/ContentTemplate.vue
src/components/Sidebar.vue
src/components/feed-display/FeedItemDisplay.vue
src/components/feed-display/FeedItemDisplayList.vue
src/components/feed-display/FeedItemRow.vue
src/components/feed-display/VirtualScroll.vue
src/store/app.ts
tests/Unit/Controller/PageControllerTest.php

* Resolves: #2940 
This PR replaces the current display options and adds a screen reader optimized mode
This are the new settings:
display mode: default, compact, screenreader
split mode: vertical, horizontal, off
The screen reader mode uses a single column layout with rendering the original article in the list.
This PR needs to convert the old expand/compactExpand settings:
compact 0 -> displaymode 0, splitmode 0
compact 1, compactExpand 0 -> displaymode 1, splitmode 0
compact 1, compactExpand 1 -> displaymode 1, splitmode 1
@SMillerDev @Grotax where can I find how the conversion should be made?  
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md …

Display modes and screen reader mode

---

CHANGELOG.md
src/components/feed-display/FeedItemDisplay.vue
src/store/item.ts

* Resolves: #758
* Resolves: #2945
* Related: #2949 
* fix: Embeded images are all scaled to max
* fix: If an article doesn't have title, there's no link to the article

Fixes 25.0.3

---

CHANGELOG.md
src/components/Sidebar.vue

This restores v24's behavior that hasn't been implemented in v25.
Before release 25 there had to be more than 50 feed update errors so that a feed was marked. In v25 every single update error results in a red marking which can be annoying as everybody knows that download errors can happen now and then.

Show red error bubble only if more than 50 updates failed.

---

CHANGELOG.md
src/components/AddFeed.vue
src/components/ShareItem.vue
src/components/feed-display/FeedItemDisplay.vue
src/components/feed-display/FeedItemRow.vue

* Related: #2920 
* Related: #2102 
This PR adds some accessibility improvements and a bugfix for the newly introduced vertical split compact mode.
- set correct input focus when opening `AddFeed` or `Share` modals
- add item url to open website button aria label for screen readers
- allow using `toggle starred` and `mark read` icons with keyboard
- remove close button from list items in screen reader mode
- mark read on scroll marks visible items as read using vertical compact display mode

Accessibility improvements

---

CHANGELOG.md
src/components/feed-display/FeedItemDisplay.vue
src/components/feed-display/FeedItemDisplayList.vue
src/components/feed-display/VirtualScroll.vue
src/components/modals/HelpModal.vue

* Related: #2939 
This PR will change the article navigation in screen reader mode to workaround problems with the dynamic scroll and screen reader software.
When switching between articles with the keyboard shortcuts the article title link will be focused as starting point for reading the article.
If the focus switches to the previous or next article, for e.g. when using tab or other navigation keys, the article will be automatically selected, to prevent the navigation from getting lost.

feat: emulate structural heading navigation to workaround problems with screen readers and the dynamic scroll

---

CHANGELOG.md
lib/Fetcher/Client/FeedIoClient.php
lib/Service/FeedServiceV2.php
src/components/AddFeed.vue
src/dataservices/feed.service.ts
src/store/feed.ts
tests/javascript/unit/components/AddFeed.spec.ts
tests/javascript/unit/services/feed.service.spec.ts

This PR add an error message to the add feed dialog to show what happens if a feed can't be added.
It also adds error handling to the backend for 403 forbidden errors and errors during auto-discover to give the user reasonable information in the server log and in the web-ui.

Show error message received from the API when adding feed

---

CHANGELOG.md
src/components/MoveFeed.vue
src/components/Sidebar.vue
src/components/SidebarFeedLinkActions.vue
src/components/feed-display/FeedItemDisplay.vue
tests/javascript/unit/components/Sidebar.spec.ts

This PR prevents the move feed dialog from closing unexpectedly and change the style to match the other modals.
It also change that articles which doesn't use the full article width will be further centered, so all articles align same.

Fix move feed dialog closes unexpectedly and small style fixes

---

CHANGELOG.md
appinfo/info.xml

Changed
- show error message in add feed dialog and keep it open if the feed could not be added (#2988)
- keep margins the same even if an article does not use max width (#2995)
Fixed
- adding feed via web-ui always use auto-discover (#2988)
- show 403 forbidden errors when fetching feeds (#2988)
- prevent move feed dialog from being closed unexpectedly (#2995)
- don't abort `opml` import when a single feed exists or can't be added (#2996)

Release 25.1.2

---

CHANGELOG.md
docs/api/api-v1-2.md
docs/api/api-v1-3.md
lib/Db/Feed.php
lib/Fetcher/FeedFetcher.php
lib/Migration/Version250000Date20240817095614.php
lib/Migration/Version250200Date20241219085150.php
tests/Unit/Db/FeedTest.php
tests/Unit/Fetcher/FeedFetcherTest.php
tests/api/feeds.bats
tests/test_helper/feeds/Nextcloud.rss
tests/test_helper/feeds/heise.xml
tests/test_helper/feeds/no_guid_feed.xml

This is a first step to modernize the update cycle, the idea is to not fetch feeds on a fixed schedule.
feed-io provides a function to calculate the timestamp when an update would make sense.
This timestamp gets stored in the feed model now and can be used in a future PR to decide if we update a feed or not.
This is of course with feeds in mind that work like "normal" news feeds there might be special use case feeds that do not work well with this approach. But News does not claim to be the perfect solution for everything it is a feed reader and server api that helps users to consume feeds from different sources. 
This also adds a new field to the API: nextUpdateTime contains a timestamp which indicates when the next update is due
```json
{
"feeds": [
{
"added": 1734689445,
"faviconLink": …
```

Add new field nextUpdateTime to feed

---

CHANGELOG.md
src/components/Sidebar.vue

* Resolves: #2882
* Resolves: #2920 
With Nextcloud Vue 8.22.0 (#3003) the refs for the NcActionButton action menus are fixed, for single action it must be set itself.

fix: TypeError: this.$refs.actions.$refs.menuButton is undefined when tabbing through feeds and folders

---

CHANGELOG.md
appinfo/info.xml
docs/admin.md
docs/user.md
lib/AppInfo/Application.php
lib/Db/Feed.php
lib/Fetcher/FeedFetcher.php
lib/Service/FeedServiceV2.php
src/components/AdminSettings.vue
tests/Unit/Service/FeedServiceTest.php
tests/api/feeds.bats
tests/javascript/unit/components/AdminSettings.spec.ts
tests/updater/update.bats

This changes the logic of updating/fetching a feed to check for the nextUpdateTime before the the update is executed.
If that time is not reached yet the feed is not updated. This is mainly a advantage for feeds that are updated rarely and will therefore receive less requests. For the nextcloud instance this is also a benefit because feed updates that are likely not needed are skipped, which saves compute time.
The default minimum for an active feed is "in 1 hour" which means it will be updated in hour again.
Also added a setting to disable this, mostly for testing but I can also imagine that in the beginning or for certain use cases people want to disable this.
Builds on top of #2993 
- …

Update feed only if nextUpdateTime has been reached

---

docker/Dockerfile
docker/README.md
docker/docker-compose.yml

Just an update for the docker dev environment and adding sqlite 3 plus some documentation for new people.

Update for the docker dev env

---

CHANGELOG.md
appinfo/info.xml

Releasing this as beta because I'm quite confident that it will work fine but who knows.
Also for the first time the version pattern is according to the docs of nextcloud and what most apps use, plus this release will not be marked as nightly, see https://github.com/nextcloud/news/pull/2894
Changed
- API add new field to Feed that indicates when the next update will be done "nextUpdateTime" (#2993)
- Change logic to update feed only if the nextUpdateTime has been reached (#2999)
- Add setting to disable the usage of nextUpdateTime (#2999)
Fixed
- `TypeError: this.$refs.actions.$refs.menuButton is undefined` when tabbing through feeds and folders (#3004)
- [Sign-off …

Release 25.2.0-beta.1

---

.devcontainer/README.md
.devcontainer/devcontainer.json
docs/developer.md

Just a fix to the devcontainer to make it work and some docs about it.

Fix devcontainer, update docs

---

.github/workflows/api-integration-tests.yml
.github/workflows/api-php-tests.yml
CHANGELOG.md
lib/Utility/OPMLImporter.php

* Resolves: #2896
Checked the code and indeed when News exports to opml we set both title and text to the feed title.
So I guess some exporters might choose to only put it in text. So let's check for title first and if that is missing take text :)

OPML If title field does not exist look for text

---

CHANGELOG.md
lib/Config/FetcherConfig.php
lib/Fetcher/FeedFetcher.php
tests/updater/update.bats

The calculations feed-io does can lead to high values that would delay the next update for too long.
Maybe the calculations done in feed-io could be improved but this provides a simple fix by limiting the delay to maximum one day.
Adds SLEEPY_DURATION to FetcherConfig and use it for the nextUpdateTime calculation.
[#3013](https://github.com/nextcloud/news/discussions/3013)

Limit the delay for an update to "in one day"

---

CHANGELOG.md
lib/Db/Feed.php
src/components/Sidebar.vue
src/components/modals/FeedInfoTable.vue
tests/Unit/Db/FeedTest.php

* Related: #3013 
* Related: #2999
Add a feed information table, accessible through the user settings that show relevant info about feed updates.

feat: Add a feed information table that show update dates

---

CHANGELOG.md
src/components/Sidebar.vue
src/components/modals/FeedInfoTable.vue

- style fixes in settings section and feed info table
- sorting in the feed information table changes also the original sorting

fix: sorting bug and style fixes with the feed info table

---

CHANGELOG.md
appinfo/info.xml

- style fixes in settings section and feed info table (#3024)
- sorting in the feed information table changes also the original sorting (#3024)

Release 25.2.0-beta.3

---

CHANGELOG.md
src/components/modals/FeedInfoTable.vue

Especially for the next update time feature explanations for the values in the feed information table seems helpful.
Also small style fixes.

Add  descriptions to Feed Information Table

---

CHANGELOG.md
docker/README.md
lib/Config/FetcherConfig.php
tests/Unit/Config/FetcherConfigTest.php

* Related: https://github.com/nextcloud/news/issues/2982
Add debug logging for the proxy configuration
And add nano to the docker image to edit files.

Fix issue that proxy port is removed if it matches the standard port

---

CHANGELOG.md
lib/Controller/ImportController.php
src/components/Sidebar.vue

* Related: #3035  
Return opml import error message as api response to show it in the web-ui.

feat: show error message from opml import in web-ui

---

CHANGELOG.md
docs/admin.md
lib/AppInfo/Application.php

* Resolves: # 
Due to the potential issues and complaining by users I prefer to disable this feature by default.
For me it works as is and reduces the fetching of the feeds that are less active.

disable new setting nextUpdateTime by default

---

lib/Service/FeedServiceV2.php

* Resolves: # 
I noticed that the current logger will show the variables only in the details hidden in a menu.
Which is fine for the timestamps I guess.
But I think at least the url should show up in the logs.

show url directly in log message

---

docs/user.md

* Related: #3000
Starting with the user documentation.

docs: add documentation for feed options and settings for the web-ui

---

CHANGELOG.md
src/store/folder.ts

fix: show error on folders only if at least one feed has more than eight errors

---

CHANGELOG.md
src/components/ContentTemplate.vue
src/components/feed-display/FeedItemDisplay.vue
src/components/feed-display/FeedItemDisplayList.vue
src/components/feed-display/FeedItemRow.vue

Uses new `mobileLayout` prop of `NcAppContent` from https://github.com/nextcloud-libraries/nextcloud-vue/pull/6364 and sets to `horizontal-split`
Adds Navigation Arrows to top of `FeedItemDisplay` to go to next/previous item when in mobile view
Depends on https://github.com/nextcloud-libraries/nextcloud-vue/pull/6364

Improve mobile view by using `horizontal-split` mobile layout

---

CHANGELOG.md
docs/admin.md
lib/Config/FetcherConfig.php
lib/Fetcher/FeedFetcher.php

As discussed in #3013 the nextUpdateTime feed-io calculates is not always accurate and can push the next update too far in the future.
https://github.com/alexdebril/feed-io/pull/434 will fix some problems, but for feeds with sporadic articles an accurate calculation is impossible.
Therefore, the maximum next update time should be limited to 24 hours, which is also the value used when a feed is recognized as sleeping.
This PR also sets the sleepy feed detection to the default of 7 days, which should work for most feeds. A small value like one or two days can cause feeds that have for example no posts on the weekend, not being downloaded until monday evening.
- [Sign-off …

Limit the max nextUpdateTime delay to 24 hour

---

Makefile

Since css is no longer needed and does no longer exist the copy command needs to be modified

Fix build pipeline

---

tests/command/opml.bats
tests/test_helper/feeds/Nextcloud.opml

The  integration tests currently fails because the external feed https://nextcloud.com/blog/static-feed/ used in the opml test is actual not valid.
Changes:
* use local feed like the other tests
* add opml import test

Fix bats integration opml test

---

CHANGELOG.md
composer.json
composer.lock
lib/Config/FetcherConfig.php
lib/Fetcher/FeedFetcher.php
tests/Unit/Config/FetcherConfigTest.php

* Resolves: #3087
Let's see if it works with guzzle.

replace net_url2 with guzzle

---

CHANGELOG.md
appinfo/info.xml

- preg_replace_callback(): Compilation failed: digits missing after \x or... (#3105)

Release 25.3.0-beta.2

---

CHANGELOG.md
lib/Config/FetcherConfig.php
tests/Unit/Config/FetcherConfigTest.php

* Resolves: #3114
If guzzle finds no schema it only adds // therefore we default to http

fix 3114, proxy url without schema

---

CHANGELOG.md
src/store/feed.ts

* Resolves: #3097
Actual the frontend gets the feeds sorted from the backend, but because the default for case sensitivity depends on the used database and the nextcloud QueryBuilder seems to have no option, sort the feeds in the frontend.

fix: sort feeds case-insensitive

---

CHANGELOG.md
package-lock.json
package.json
src/components/Sidebar.vue
src/components/feed-display/FeedItemDisplay.vue
src/components/feed-display/FeedItemDisplayList.vue
src/main.js

Related: #2916
Switching to useHotKey solves several problems with text-input fields, it also respects the  `disable all keyboard shortcuts` accessibility setting and is vue3 ready due the upcoming nextcloud/vue v9 update.

Switch to useHotKey from @nextcloud/vue

---

.github/workflows/api-integration-tests.yml
.github/workflows/api-php-static-code-check.yml
.github/workflows/api-php-tests.yml
.github/workflows/build-release.yml
.github/workflows/frontend-nodejs-tests.yml
.github/workflows/updater-test.yml
CHANGELOG.md
appinfo/info.xml

The change in #3142 don't work with Nextcloud 29, so with the next version no keyboard shortcut will work here.
The upcoming update to nextcloud/vue v9 will also no longer work with Nextcloud 29.
Nextcloud 29 is also EOL this month [Maintenance-and-Release-Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule)

Drop support for Nextcloud 29

---

CHANGELOG.md
src/components/AdminSettings.vue
src/components/feed-display/FeedItemDisplay.vue
src/components/feed-display/FeedItemRow.vue
src/utils/dateUtils.ts
tests/javascript/unit/components/feed-display/FeedItemDisplay.spec.ts
tests/javascript/unit/components/feed-display/FeedItemRow.spec.ts

* Resolves: #3147
This PR fixes incorrect relative date strings like '1 days ago' or '1 years ago'.
It also changes that the nextcloud user settings locale is used, instead of the browser locale.

fix: use @nextcloud/moment for formatted date strings

---

CHANGELOG.md
package-lock.json
package.json
src/components/ContentTemplate.vue
src/components/feed-display/FeedItemDisplay.vue
src/components/feed-display/FeedItemDisplayList.vue

* Resolves: #2866
* Resolves: #2904
* Related: #3136
This PR updates @nextcloud/vue to 8.26.0, which contains an upstream fix https://github.com/nextcloud-libraries/nextcloud-vue/pull/6261

deps: update nextcloud/vue 8.26.0

---

CHANGELOG.md
appinfo/info.xml

- Drop support for Nextcloud 29 (#3146)
- respect global `disable all keyboard shortcuts` setting (#3142)
- disable shortcuts in input fields from global overlays (e.g. Nextcloud assistant) (#3142)
- fix relative date strings (#3149)
- Switching between folders in compact mode doesn't close actual selected item (#3150)
- current selected article is removed from the list after showing details in mobile mode (#3150)

Release 26.0.0-beta.1

---

src/components/feed-display/FeedItemDisplayList.vue
src/components/feed-display/VirtualScroll.vue

This is a hotfix for the last virtual scroll changes in  #3153 , where the scroll list is not updated by automatic or manual refresh.

fix: item list not updated by automatic or manual refresh

---

CHANGELOG.md
appinfo/routes.php
src/routes/index.ts

* Resolves: #3122
To use the html5 history mode, all routes needs to be configured in appinfo/routes.php.
The subscriber url `https://yourdomain.com/nextcloud/index.php/apps/news?subscribe_to=` works again.
The question would be whether we should change this in the future and use a route like /subscribe.
[Different History modes](https://router.vuejs.org/guide/essentials/history-mode)

refactor: use html5 history mode

---

CHANGELOG.md
appinfo/info.xml

* Resolves: # 
Changed
- Migrate frontend to Vue3 (#3163)
- Migrate from webpack to vite (#3163)
- Migrate from jest to vitest (#3163)
Fixed
- subscribe_to URL path has changed (#3159)
- change update mode menu text and icon in feed action menu (#3163)

Release 26.0.0-beta.3

---

CHANGELOG.md
src/App.vue
src/components/feed-display/FeedItemDisplayList.vue
src/components/routes/All.vue
src/components/routes/Feed.vue
src/components/routes/Folder.vue
src/components/routes/Starred.vue
src/components/routes/Unread.vue
src/dataservices/item.service.ts
src/store/feed.ts
src/store/item.ts
tests/javascript/unit/components/feed-display/FeedItemDisplayList.spec.ts
tests/javascript/unit/store/item.spec.ts

Switching between the individual routes can lead to the item list being either empty or filled with wrong items, which seems to be even worse with vue3.
To fix this I changed the following:
- synchronise watchers to prevent incorrect items from being displayed when changing routes
- remove counterproductive debounce and make sure to skip old responses
- remove the special role of the starred route and update starred counters from feeds fetching response

fix: possible race conditions when switching routes

---

CHANGELOG.md
src/components/Sidebar.vue
src/components/modals/FeedInfoTable.vue

* Resolves: #3117 
To clarify the opml import process for users that have the default setting to not show all articles, the feed info table is opened during import with a loading icon. Once the import is complete, all imported feeds can be seen in the table.
Also the import/export URLs that are broken since #3159 have been fixed.

feat: show feed info table during opml import

---

CHANGELOG.md
appinfo/info.xml

* Resolves: # 
- Open the feed info table during opml import to show what has been imported after completion (#3169)
- Wrong or none items in list after switching feed or folder (#3168)
- opml import/export not working after vue router changes (#3169)

Release 26.0.0-beta.4

---

.github/dependabot.yml
package-lock.json
package.json

This PR adds groups to the npm dependabot config to avoid conflicts when updates for coupled  dependencies like `vitest` and `@vitest/coverage-istanbul` are available.
I also added the missing direct dependency for `vite`.

Actions dependabot groups

---

CHANGELOG.md
src/components/feed-display/FeedItemDisplayList.vue
src/components/routes/Unread.vue
tests/javascript/unit/components/feed-display/FeedItemDisplayList.spec.ts
tests/javascript/unit/components/routes/All.spec.ts
tests/javascript/unit/components/routes/Feed.spec.ts
tests/javascript/unit/components/routes/Folder.spec.ts
tests/javascript/unit/components/routes/Starred.spec.ts
tests/javascript/unit/components/routes/Unread.spec.ts

The fix in d9575ad only moved the timing problem to another place. Now it can happen that the first selected item could disappear from the list if you change from another type of route, e.g. from feed to folder.
I removed the watch completely and let the item list update though a computed function,which fixed the problem now.
I also add additional unit tests especially for the item list creation, which showed the previous problem.

fix: first selected item can disappear from the list

---

CHANGELOG.md
src/components/feed-display/FeedItemRow.vue

* Resolves: #3185 
When using vertical-split/compact mode item intro text and date was hidden, this PR enables the intro text and shows the date when enough space are available.

feat: show intro and date if enough space in compact mode

---

CHANGELOG.md
appinfo/info.xml

* Resolves: # 
- show intro and date if enough space in compact mode (#3186)
- since `26.0.0-beta.4` the first selected item can disappear from the list if you change from another type of route, e.g. from feed to folder (#3178)

Release 26.0.0-beta.5

---

src/components/Sidebar.vue
src/components/SidebarFeedLinkActions.vue

Close action menu before changing navigation item to avoid unexpected errors from the popover component like `TypeError: this.getPopoverContentElement() is undefined`

fix: close action menu before renaming or deleting navigation item

---

CHANGELOG.md
appinfo/info.xml

- content splitter position not recognized when reloading app (#3193)
- feed/folder action menu does not close when clicked outside (#3193)
- fix feed url in details view (#3193)

Release 26.0.0

---

src/components/Sidebar.vue
src/components/SidebarFeedLinkActions.vue
src/components/feed-display/FeedItemDisplayList.vue
src/components/feed-display/VirtualScroll.vue
src/components/routes/All.vue
src/components/routes/Feed.vue
src/components/routes/Folder.vue
src/components/routes/Starred.vue
src/components/routes/Unread.vue
src/store/item.ts
src/utils/itemFilter.ts
src/utils/unreadCache.ts
tests/javascript/unit/components/SidebarFeedLinkActions.spec.ts
tests/javascript/unit/components/feed-display/FeedItemDisplayList.spec.ts
tests/javascript/unit/components/routes/All.spec.ts
tests/javascript/unit/components/routes/Feed.spec.ts
tests/javascript/unit/components/routes/Folder.spec.ts
tests/javascript/unit/components/routes/Starred.spec.ts
tests/javascript/unit/components/routes/Unread.spec.ts

Related: #3191 
This PR moves the sorting and filter logic to the route components, where they actually belong, as sorting or filtering only takes place via the api calls with their parameters like showAll and oldestFirst.
Among other things, this is necessary so that all child components can easier access the same array of feed items. This will also help with implementing keeping details view when switching between feeds and folders in #3191 
The items are filtered and re-sorted in the route component depending on the settings. The sorting is necessary because the array allItems contains blocks of items with different sorting due to possible individual feed sorting.
- [Sign-off …

refactor: Feed item list filtering and sorting

---

CHANGELOG.md
src/components/feed-display/FeedItemDisplay.vue

* Resolves: #3210
This PR adds  style fixes for `<blockquote>`, `<pre>` and `<code>` in articles and now keeps the action bar position when scrolling.

fix: style fixes for articles

---

CHANGELOG.md
appinfo/routes.php
src/components/AdminSettings.vue

* Resolves: #3216
Since the router mode change the explore url can't be called directly.
I also changed the admin setting description to force a new translation. The translation seems to be broken from the beginning. The apostrophe should normally be no problem, maybe a bug when the text was initially be created.
`l10n/en_GB.js:    "If given, this service" : "If given, this service",`

fix: explore url does not work when called directly

---

CHANGELOG.md
src/components/AddFeed.vue

The radio switches in the add feed dialog cannot currently be switched.

fix: radio switches in add feed dialog not working

---

CHANGELOG.md
src/components/feed-display/FeedItemDisplay.vue
tests/javascript/unit/components/feed-display/FeedItemDisplay.spec.ts

319a8ff fixed the url but set it only initially when showing an article, it don't change in merged routes when navigating between articles.

fix: incorrect feed url in article view when navigating in merged routes such as unread or a folder

---

CHANGELOG.md
package-lock.json
package.json
src/components/feed-display/FeedItemDisplayList.vue
src/components/feed-display/FeedItemRow.vue

* Resolves: #2826 
This PR enables the swipe down gesture to refresh the item list (credits to @nextcloud/vue for the handleSwipe function).
It have also moved the action buttons to a three dot menu on small devices, so that the headlines have more space.

feat: add swipe down gesture to refresh item list on mobile devices

---

CHANGELOG.md
lib/Fetcher/Client/FeedIoClient.php
lib/Fetcher/FeedFetcher.php
lib/Service/FeedServiceV2.php

* Resolves: #3199
This PR changes that the If-Modified-Since Header is only set on feed creation if the feed server supports it and in general the header is only set when it is a valid date, which fixes problems with reddit and maybe other content providers.
This helps also with the forced modfiedSince Date '1800-01-01' from feed-io workaround (#676, https://github.com/alexdebril/feed-io/issues/308).
Since news actual uses a local copy of the FeedIo Client, this also should be done in feedio, if we switch to the originally client someday.
Also feedio uses '1970-01-01' when discover a feed, which also will have that issue.
- [Sign-off …

fix: only use Last-Modified header if a feed supports it

---

CHANGELOG.md
appinfo/routes.php
src/components/ContentTemplate.vue
src/components/Sidebar.vue
src/components/feed-display/FeedItemDisplay.vue
src/components/feed-display/FeedItemDisplayList.vue
src/components/feed-display/FeedItemRow.vue
src/components/routes/Recent.vue
src/routes/index.ts
src/store/item.ts
tests/javascript/unit/components/ContentTemplate.spec.ts
tests/javascript/unit/components/feed-display/FeedItemDisplay.spec.ts
tests/javascript/unit/components/feed-display/FeedItemDisplayList.spec.ts
tests/javascript/unit/components/feed-display/FeedItemRow.spec.ts
tests/javascript/unit/store/item.spec.ts

This PR adds a new list that shows the last 20 recently viewed articles, which will be helpful if you already switched the feed and want to go back to show the article again or if you want to star it for example.
This is a temporary list which only relies on the frontend and is reset when reloading the app in the browser or by pressing 'r'.

feat: add recently viewed list

---

CHANGELOG.md
src/components/ContentTemplate.vue
src/components/feed-display/FeedItemDisplayList.vue
src/components/feed-display/FeedItemRow.vue
src/components/routes/All.vue
src/components/routes/Feed.vue
src/components/routes/Folder.vue
src/components/routes/Recent.vue
src/components/routes/Starred.vue
src/components/routes/Unread.vue
tests/javascript/unit/components/feed-display/FeedItemDisplayList.spec.ts

* Resolves: #3252
This PR adds a refresh button to the list header

feat: add refresh button to list header

---

CHANGELOG.md
src/store/feed.ts

* Resolves: #3255 (hopefully)
I don't know how it can happen, but in case of #3255, when the counter initially shows this huge values, the only explanation is that it gets at least one feed unread counter as string.
So I have added checks that make sure it is treated as number.

fix: Unread counter displays a huge number of unread posts

---

CHANGELOG.md
lib/Fetcher/FeedFetcher.php

* Resolves: #2609
Hopefully this will have the same effect on the content

Fix Handling HTML entities via mbstring is deprecated

---

CHANGELOG.md
lib/Fetcher/FeedFetcher.php

* Resolves: #2378
So I (and Copilot) refactored this part of the code to also include a check of the feeds link that was one suggestion in #2378 I also tested the bbc feed logo again and what happens if we allow non square images and it results in the image being repeated twice I assume to fill the square space so you cant identify anything anyway.
But this change will add favicons to a lot of more feeds that use some cdn to serve their feed, of course we still have the issue that some websites will block News but well ... at least the few reported that I tested except one got an image now.
You can almost not see the NYT but that is because they have a black icon without background. That BBC got the three back dots surprised me I always thought red was their color but turns out the …

Refactor favicon fetching to also check feed link

---

.github/workflows/api-integration-tests.yml
.github/workflows/api-php-static-code-check.yml
.github/workflows/api-php-tests.yml
.github/workflows/build-release.yml
.github/workflows/frontend-nodejs-tests.yml
.github/workflows/updater-test.yml
CHANGELOG.md
appinfo/info.xml

Changed
- Drop Support for Nextcloud 30 (#3294)
- Add Support for Nextcloud 32 (#3294)
- If feed has no favicon and no logo News will check the linked website of the feed (#3271)
Fixed
- Unread counter displays a huge number of unread posts (#3267)
- Nextcloud language setting is not respected for numbers and dates (#3278)
- Handling HTML entities via mbstring is deprecated (#3269)

Release 27.0.0-beta.1

---

package-lock.json
package.json

nextcloud vite-config 2.4.0 adds support for vite 7, but doesn't compile with it.
2.5.0 needs minimum vite version 7.1.4, so update both to be up to date again.

deps: update vite to 7.1.5 and @nextcloud/vite-config to 2.5.0

---

CHANGELOG.md
lib/Controller/FeedController.php
src/components/SidebarFeedLinkActions.vue
src/components/modals/FeedInfoTable.vue
src/dataservices/feed.service.ts
src/store/feed.ts
src/types/Feed.ts
tests/Unit/Controller/FeedControllerTest.php

* Resolves: #1625 
This PR adds an option to the feed action menu, to enable/disable sync of the selected feed. The sync is controlled by feed.preventUpdate which exist already on the backend.
The feed info table will show "Sync disabled" as last update time to keep an overview of which feeds are deactivated.

feat: add option to enable/disable sync of a feed

---

CHANGELOG.md
lib/Scraper/Scraper.php

Related: #3319
Seems like we forgot to adjust the scraper to also use the new function.

fulltext scraper did not use new user agent

---

.github/workflows/api-integration-tests.yml
.github/workflows/updater-test.yml

This will fix the problems in the updater-test and api-integration-tests  workflow, that dependencies are not found.
```
Get:9 http://azure.archive.ubuntu.com/ubuntu noble/universe amd64 httpie all 3.2.2-1 [93.9 kB]
Ign:2 https://archive.ubuntu.com/ubuntu noble-updates/main amd64 dpkg-dev all 1.22.6ubuntu6.2
Ign:3 https://archive.ubuntu.com/ubuntu noble-updates/main amd64 libdpkg-perl all 1.22.6ubuntu6.2
Err:2 https://security.ubuntu.com/ubuntu noble-updates/main amd64 dpkg-dev all 1.22.6ubuntu6.2
404  Not Found [IP: 52.147.219.192 80]
```
- Changelog entry added for all …

fix: update package lists before installing httpie

---

CHANGELOG.md
appinfo/routes.php
lib/Search/ItemSearchProvider.php
src/components/routes/Item.vue
src/dataservices/item.service.ts
src/routes/index.ts
src/store/item.ts
tests/Unit/Search/ItemSearchProviderTest.php

This PR adds a new route (/item/:id) to open an article directly and changed the item search to use the new route.

feat: Open article from unified search result
