nextcloud/news

explore/feeds/feeds.en.json
Add Nextcloud Planet to the feeds. Fix news-app update feed as well.
Fixes https://github.com/nextcloud/news/issues/7
=> Add Nextcloud sources to explore feeds

docs/developer/External-Api.md
[Rendered](https://github.com/nextcloud/news/blob/apiv2/docs/developer/External-Api.md)
@phedlund @David-Development please comment :)
=> API v2 up for discussion 

l10n/.tx/config
=> adjust config for nextcloud

lib/Explore/feeds/feeds.de.json
=> fix explore feed urls, add feed suggestion

templates/part.settings.php
=> Add settings string

README.md
=> Added py3status in README

lib/Fetcher/FeedFetcher.php, lib/PostProcessor/LWNProcessor.php, tests/Unit/Fetcher/FeedFetcherTest.php
Allows loading full lwn.net subscriber articles in the feed by setting the username and password for the feed and enabling full text downloading.
cc @BernhardPosselt
=> Add postprocessor for getting lwn.net subscriber articles

css/navigation.css
Will be fixed with nextcloud/server#3150
Fixes https://github.com/nextcloud/news/issues/56 properly. Please review @MariusBluem @BernhardPosselt @nextcloud/news :)
=> fix different look of navigation bar

appinfo/info.xml, js/gui/ExternSubscription.js
Feed subscription and Updater link in app info had OC references. changed to NC.
=> change OC references

composer.json
should fix issue #83 
and also see ezyang/htmlpurifier#98
=> Update version of htmlpurifier to v4.9.2

templates/part.navigation.folder.php
=> Fix of #156 for folders

js/gui/KeyboardShortcuts.js
I've noticed this behavior too, it really annoys.
=> Fix for #54

templates/admin.php, templates/part.content.warnings.php, templates/part.settings.php
Improvements from transifex discussions
=> Rakekniven patch 1

lib/Cron/Updater.php
Call the beforeUpdate() method before calling update() in cron updater (see #172).
=> Call cron beforeUpdate() before update() (#172)

.travis.yml, Makefile, appinfo/database.xml, composer.json, composer.lock, js/tests/unit/controller/ContentControllerSpec.js, tests/Integration/IntegrationTest.php, tests/Unit/Controller/PageControllerTest.php, tests/Unit/Service/StatusServiceTest.php
* Use stable12 branch
* Use psql 9.4, as precise container on travis doesn't support 9.5
* Create psql role
* Fix several tests
* Require phpunit 5, nextcloud tests not compatible with phpunit 6
* Shorten db indices to satifisy app:check-code
Fixes #170, #171
=> Fix travis build

CONTRIBUTING.md, composer.json, composer.lock, docs/README.md
* htmlpurifier 4.9.3 fixes running under php 7.1
* picoFeed moved to miniflux/picoFeed, rename references
=> Update htmlpurifier and picoFeed

css/navigation.css, templates/part.navigation.feed.php, templates/part.navigation.folder.php
After https://github.com/nextcloud/server/pull/6399
=> App to css guidelines

README.md
=> Update feeds are not updated help for v12

js/controller/NavigationController.js, templates/part.navigation.feed.php
This pull request adds a new link "open feed url" to the navigation. See issue #199
=> add link to open feed-url (fixes #199)

README.md
=> Fix debug instructions

css/content.css, css/settings.css, js/directive/NewsScroll.js, js/gui/KeyboardShortcuts.js, templates/index.php, templates/part.content.php
=> Stable13 fixes

README.md
https://newsboat.org/releases/2.10.2/docs/newsboat.html#_owncloud_news_synchronization
=> Add newsboat compatible client to README.md

Makefile
Also fixes potentially updated packages where they shouldn't be.
=> Remove development dependencies from archive

.github/no-response.yml, .github/stale.yml
These probably still need to be enabled in the the repo settings but hopefully it'll clean up the issue list a bit.
=> Add github bots for issues

.github/no-response.yml, .github/stale.yml, README.md, docs/configuration.md, docs/faq/README.md, docs/install.md
The current readme is a multipage document, meaning that not a lot of people read the full thing. Hopefully this pull request makes that a bit better.
=> Cleanup the README

css/app.css, js/directive/NewsScroll.js
- mark as read on scroll fix
- items flashing before app load fix
=> Compact mode scroll fix + nc14 last patch

docs/install.md
make it easier for the users to find the news app in the app store.
=> add info where to find news app in app store

css/content.css, css/mobile.css
Signed-off-by: John Molakvoæ (skjnldsv) <skjnldsv@protonmail.com>
Fix #324
=> Fix firefox wide screen and mobile view

js/package-lock.json, lib/Controller/ExportController.php, tests/Unit/Db/FeedTest.php
This will add a date to the exported subscriptions.opml:
```
subscriptions-YEAR-MONTH-DAY.opml
```
Closes  #286
=> add date to export .opml

CHANGELOG.md, appinfo/info.xml
@skjnldsv @SMillerDev Are you fine with releasing those changes as 13.0.2? Mainly because we should release the fix of the signature (#347)
=> 13.0.2 & changelog

lib/Db/Feed.php, lib/Db/Folder.php, lib/Db/Item.php
This fixes https://github.com/nextcloud/news/issues/350#issue-369283392
Signed-off-by: Detlev Zundel <dzu@member.fsf.org>
=> Fix lastModified to be a string rather than an integer.

css/admin.css, css/app.css, css/content.css, css/navigation.css, css/shortcuts.css
This merge request makes it so news uses the color variables defined by nextcloud.
Nextcloud 14 added accessibility themes (https://nextcloud.com/blog/nextcloud-14-the-most-accessible-nextcloud-ever/)
You can enable the high contrast one at /settings/user/accessibility, or you can add custom css to change the color variables manually.
=> * Style: Allow to be themed using nextcloud's predefined CSS variables

lib/AppInfo/Application.php
I just found that on my local instance.
- removed functions which call the container to call container directly - simplifies the call stack as there are less functions to call
- defined argument and response types (PHP 7)
- removed configuration of AppConfig as its not existing anymore
The class is about half of the size now. Haven't really tested it, its just about code style, lets see what CI says.
=> Simplified Application class

css/content.css, css/explore.css, css/navigation.css, css/settings.css
Replace some hardcoded colors with variables.
=> CSS: Add some dark-theme fixes

js/.jshintrc, js/app/App.js, js/app/Config.js, js/app/Run.js, js/controller/AppController.js, js/controller/ContentController.js, js/controller/ExploreController.js, js/controller/NavigationController.js, js/controller/SettingsController.js, js/service/FeedResource.js, js/service/ItemResource.js, js/service/OPMLImporter.js, js/service/OPMLParser.js, js/service/Resource.js, templates/part.content.warnings.php
Codestyle cleanup for JS, fixing the documentation references: 
https://github.com/SMillerDev/news/blob/222de718c7b16f0f844c86897c1b7cb1877015de/templates/part.content.warnings.php#L6 and making the notifications dismiss slower: https://github.com/nextcloud/news/compare/master...SMillerDev:error_fix?expand=1#diff-678b16716b93e2a29821bc29c0496f56R76
=> Cleanup JS and prolong error notification

CHANGELOG.md, appinfo/info.xml
Some fine wine... I mean bug-fix release that is going to fix some nasty bugs.
=> Release 13.1.1

css/content.css
=> No background on active item

js/directive/NewsSearch.js
=> fix search

CHANGELOG.md
=> Update the Changelog

CHANGELOG.md, appinfo/info.xml
Changed
- The active item is now highlighted by a thin orange line #434
Fixed
- Highlight in compact mode #109
- Prevent raw angular templates from flashing on page load #429
- HTML elements where not rendered #428
- Provide UserAgent to prevent HTTP 403 errors #428
=> Release 13.1.2

docs/maintenance.md
This is a work in progress but outlines some rules for the people that see this repo and aren't just users. I'm very much open to suggestions.
=> Write down some notes about maintenance

css/content.css, css/settings.css
As suggested by @matdb in #339
=> Change href-color to a brighter blue

composer.lock, lib/Fetcher/FeedFetcher.php, tests/Unit/Fetcher/FeedFetcherTest.php
=> Fix xkcd commics

.travis.yml, Makefile, README.md
Removed code coverage test from integration test.
Added codecov support.
=> Code coverage

lib/AppInfo/Application.php
Created this from the browser, I hope it passes Travis
=> Set tmp dir as cache for favicon

CHANGELOG.md, appinfo/info.xml, composer.lock
=> Update version number

css/content.css, templates/part.content.php
=> Generate enclosure div only for audio & video

lib/Fetcher/FeedFetcher.php, tests/Unit/Fetcher/FeedFetcherTest.php
=> Get content:encoded of item if available

CHANGELOG.md, appinfo/info.xml, composer.json, composer.lock
Changed
- Get content:encoded of item if available #565
- update js and php dependencies #575
Fixed
- Generate enclosure div only for audio & video #567
=> Release 14.0.2

lib/Scraper/IScraper.php, lib/Scraper/Scraper.php
=> Allow getContent() in Scraper and IScraper to return null

AUTHORS.md, composer.lock
=> update feed-io to v4.5.1

js/controller/NavigationController.js
Youtube rss system is hiden inside their api to discourage people from using it.
I have added a step to transform automaticaly a user or a channel url like `https://www.youtube.com/user/scilabus` into its feed url: `https://www.youtube.com/feeds/videos.xml?user=scilabus`
=> Translate youtube channel and user URL into their feed

CHANGELOG.md, appinfo/info.xml, js/package-lock.json, js/package.json
Changed
- Updated js packages
Fixed
- Signature was missing
sign-app only found the private key which wasn't enough ;)
=> Release 14.1.2

.travis.yml, composer.json
The Idea was to change the test matrix in a way that would test
- legacy nc:16, php: 7.2
- stable nc:17, php 7.3
- new nc:18, php: 7.4
- dev nc:master, php:7.4
- php future
the branches need to be updated in the future
I'm open to more tests
=> new test matrix

CHANGELOG.md, appinfo/info.xml, composer.lock
- Update feed-io to v4.5.2
#607
=> Release 14.1.3

CHANGELOG.md
Changed
- update for Nextcloud 19 (#627)
- Create Czech feed examples (#664)
- Always show the unread articles "folder" (#662)
- Update feed-io to v4.5.7
=> Release 14.1.4

lib/Fetcher/Client/FeedIoClient.php, lib/Fetcher/Client/LegacyGuzzleClient.php, lib/Fetcher/Client/LegacyGuzzleResponse.php
=> If modified since

AUTHORS.md, CHANGELOG.md, appinfo/info.xml
###Fixed
- Fixed 'If-Modified-Since' causing BAD REQUEST (#684)
=> Release 14.1.6

AUTHORS.md, CHANGELOG.md, appinfo/info.xml, composer.lock, js/package-lock.json, js/package.json
- Update feed-io to v4.6.0
- Update js dependencies
=> Release 14.1.7

AUTHORS.md, CHANGELOG.md, appinfo/info.xml, js/package-lock.json, js/package.json
=> Release 14.1.9

docs/externalapi/Legacy.md
Add rtl and media attributes to Item documentation
=> Update legacy API documentation

CHANGELOG.md, composer.lock
Changed
- Update feed-io to v4.7.1
=> Release 14.1.10

CHANGELOG.md, appinfo/info.xml
Changed
- Re-release of 14.1.10
=> Release 14.1.11

templates/part.content.php
The text in intro is already escaped and also striped of html tags so i should be fine to use the unsafe binding. (fixes #559)
=> fixed double escaped intro

docs/faq/README.md
From:
"In addition people feel save when essentially they are not."
To:
"In addition, people feel *safe* when essentially they are not."
=> Fix typo in documentation

lib/Db/Item.php, tests/Unit/Db/ItemTest.php, tests/Unit/Service/FeedServiceTest.php
=> fix import with invalid guid_hash

CHANGELOG.md, appinfo/info.xml, js/admin/Admin.js, js/package-lock.json, js/package.json
- Update Interval documentation fixes #773
- Fix crash if full-text if feed doesn't provide an url #774
- Fix admin page not saving settings #776
Depends on #776
=> Release 14.2.1

CHANGELOG.md, appinfo/info.xml
Changed
- added support for Nextcloud 20 #781
Fixed
- Update interval not saved to config file #783
=> Release 14.2.2

.github/workflows/integration-tests.yml, .github/workflows/php-tests.yml, .travis.yml, Makefile
=> Test GH actions flow

CHANGELOG.md, js/package-lock.json, js/package.json
=> update js packages and update changelog

CHANGELOG.md, composer.lock, lib/AppInfo/Application.php, lib/Command/Config/FeedAdd.php, lib/Command/Config/FeedList.php, lib/Command/Config/FolderList.php, lib/Db/Folder.php, lib/Db/Item.php, lib/Fetcher/FeedFetcher.php, lib/Service/FeedServiceV2.php, lib/Service/FolderServiceV2.php, tests/Unit/Fetcher/FeedFetcherTest.php
=> Add feed autodiscovery

CHANGELOG.md
Changed
- Update feed-io to v4.7.9
- Feed autodiscovery #806
- Drop support before nextcloud 20 #794
- Move to modern SQL syntax #750
- Add management commands #804 #750
=> Release 15.0.0

lib/Service/StatusService.php, tests/Unit/Service/StatusServiceTest.php
=> fix incorrect cron recommendation

lib/Db/NewsMapperV2.php
Solves the problem mentioned in https://github.com/nextcloud/news/issues/819#issuecomment-703115844.
=> remove doubled query execute

lib/Db/Item.php
=> trim whitespaces in item titles

docs/faq/README.md
Not sure why these were there, but it's bad advice or should be read from nextcloud docs.
=> Remove bad FAQ items

lib/Db/Feed.php, lib/Db/Folder.php, lib/Db/Item.php
Fixes: https://github.com/nextcloud/news/issues/852
=> Add Type Info to Entities

lib/Db/ItemMapperV2.php, lib/Service/ItemServiceV2.php
=> fix multiple results for guid_hash

.github/workflows/integration-tests.yml, Makefile, bin/tools/check_feeds.sh, composer.lock, lib/Migration/MigrateConfig.php, lib/Migration/Version150004Date20201009183830.php
=> Fix minor issues, prepare for foreign keys and check feeds

CHANGELOG.md, appinfo/info.xml
Changed
- Update Explore page feeds and design #860
Fixed
- Fix usage of at() in unittests #864
- Fix minor issues, prepare for foreign keys and check feeds #862
- Fix multiple results for guid_hash #861
- Fix missing type info of entities #858
=> Release 15.0.4

.github/ISSUE_TEMPLATE/bug_report.md
This will make it easier to maintain the issue list
=> Make issue rules stricter.

lib/Fetcher/FeedFetcher.php, tests/Unit/Fetcher/FeedFetcherTest.php
=> Allow titles to be null

CHANGELOG.md, appinfo/info.xml
- Fix exception when title is null #869
=> Release 15.0.5

README.md
=> Remove Lifera from supported clients

.github/workflows/build-release.yml, Makefile, js/package.json
This automates the release process to the appstore, pushing to the appstore is disabled on purpose for the moment.
=> Automate release

CHANGELOG.md, appinfo/info.xml
Changed
- Updated dependencies
- New release process
=> Release 15.0.6-rc1

Makefile
=> fix app_public_cert -> app_public_crt, use printf

CHANGELOG.md, appinfo/info.xml
###Fixed
- Fix the new release process
=> Release 15.0.6-rc2

CHANGELOG.md, appinfo/info.xml
Fixed
- Fix the new release process
needs #891
=> Release 15.0.6 rc3

CHANGELOG.md, appinfo/info.xml
=> Release 15.0.6-rc4

.github/workflows/build-release.yml, CHANGELOG.md, appinfo/info.xml
There was an indentation error in the yaml.
=> Release 15.0.6 rc5

CHANGELOG.md, appinfo/info.xml
Changed
- New release approach to prevent mistakes
- Re-release of 15.0.5
=> Release 15.0.6

.github/workflows/changelog-enforcer.yml, CHANGELOG.md
=> enforce update of changelog

AUTHORS.md, CHANGELOG.md, composer.lock, lib/Command/Config/FeedAdd.php, lib/Command/Config/FeedDelete.php, lib/Command/Config/FeedList.php, lib/Command/Config/FolderAdd.php, lib/Command/Config/FolderDelete.php, lib/Command/Config/FolderList.php, lib/Command/Config/OpmlExport.php, lib/Command/ShowFeed.php, lib/Command/Updater/AfterUpdate.php, lib/Command/Updater/AllFeeds.php, lib/Command/Updater/UpdateFeed.php, lib/Service/FolderServiceV2.php, tests/Unit/Command/AfterUpdateTest.php, tests/Unit/Command/BeforeUpdateTest.php, tests/Unit/Command/ExploreGeneratorTest.php, tests/Unit/Command/FeedAddTest.php, tests/Unit/Command/FeedDeleteTest.php, tests/Unit/Command/FeedListTest.php, tests/Unit/Command/FolderAddTest.php, tests/Unit/Command/FolderDeleteTest.php, tests/Unit/Command/FolderListTest.php, tests/Unit/Command/OpmlExportTest.php, tests/Unit/Command/ShowFeedTest.php, tests/Unit/Command/UpdateFeedTest.php, tests/Unit/Utility/TimeTest.php
Add unittests for command classes
=> Command: Add unittests

.github/dependabot.yml
=> dependabot add default labels

templates/index.php
=> fix invisible feeds in root thanks @anoymouserver

CHANGELOG.md, composer.lock, lib/Controller/FeedApiController.php, tests/Unit/Controller/FeedApiControllerTest.php
Should fix #909
the signature of delete changed when @SMillerDev added the V2 services
=> fix delete api

CHANGELOG.md, composer.lock, docs/externalapi/Legacy.md, lib/Controller/AdminController.php, lib/Controller/ApiController.php, lib/Controller/FeedApiController.php, lib/Controller/FeedController.php, lib/Controller/FolderApiController.php, lib/Controller/FolderController.php, lib/Controller/ItemApiController.php, lib/Service/FeedServiceV2.php, lib/Service/FolderServiceV2.php, tests/Unit/Controller/FeedApiControllerTest.php, tests/Unit/Controller/FolderApiControllerTest.php, tests/Unit/Controller/ItemApiControllerTest.php
Some more updates to phase out the old services
=> Controllers: Use v2 services

CHANGELOG.md, appinfo/info.xml
Changed
- Added changelog enforcer action
- Stop overloading DB ids
- Unittest commands and utilities
- Upload codecoverage to codecov.io
- Use foreign keys in db
=> Release 15.1.0-rc1

composer.json, composer.lock
The repo has already a workflow for PHP 8.0 and the Nextcloud pre-release supports it as well.
=> enable PHP 8.0 to validate for NC 21

CHANGELOG.md, js/controller/NavigationController.js, templates/part.navigation.feed.php, templates/part.navigation.folder.php
=> add locale-aware sorting for folders and feeds

README.md
=> Remove IRC from the Readme

README.md
Repo was archived last release 2016
=> Remove ocNews

README.md
=> WebOS client moved to github

CHANGELOG.md, lib/Db/FeedMapperV2.php, lib/Db/FolderMapperV2.php, lib/Db/NewsMapper.php
API allowed access to folders of other users
=> fix second where overrides previous condition

docs/externalapi/Legacy.md
Tested for all endpoints which allow to input folderIds.
Also added `jsonc` to better format json examples with comments.
=> update to match folderId `null` for the root folder

CHANGELOG.md, appinfo/info.xml
Changed
- This version brings some major changes, be aware that some clients may not support this news version.
=> Release 15.1.0

.github/workflows/php-tests.yml
As it's always sqlite we can save some compute power :)
=> Remove unnecesary if clause

CHANGELOG.md, appinfo/info.xml, composer.lock
Changed
- Remove outdated folder DB code
Fixed
- Export Unread/Starred Articles gives Error Message #963
- Some events don't appear in feed #921
=> Release 15.1.1-rc1

AUTHORS.md, CHANGELOG.md, appinfo/info.xml, composer.lock
Fixed
- Handle unauthorized users #985
- Call to undefined method OCA\News\Db\FeedMapperV2::find() #981
=> Release 15.1.1-rc2

.github/workflows/frontend-tests.yml, .github/workflows/integration-tests.yml, .github/workflows/php-tests.yml
=> update nc version in actions

CHANGELOG.md, appinfo/info.xml
Changed
- Remove outdated feed DB code
- add background & hover for entries
- Improve spacing of open articles in compact mode (nextcloud/news#1017)
Fixed
- `MissingNamedParameter` exception after upgrading to NC 21 beta5 (#1030)
=> Release 15.2.0beta1

CHANGELOG.md, appinfo/info.xml
fixing the version in the changelog and in the info.xml to be more semver
=> fix changelog and version

.github/release-drafter.yml
=> first improvements for the release-drafter

CHANGELOG.md, lib/Db/Folder.php, tests/Unit/Db/FolderTest.php
=> fix opened state of folders is not restored

.github/ISSUE_TEMPLATE/config.yml
As per [GitHub's help pages](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser), following #1014.
=> Lead users to Discussions

.github/workflows/php-tests.yml, .github/workflows/static-code-check.yml
=> CI: Bump actions versions and improve statics name

CHANGELOG.md, lib/Controller/FeedApiController.php, lib/Controller/FeedController.php, tests/Unit/Controller/FeedApiControllerTest.php, tests/Unit/Controller/FeedControllerTest.php
=> Controllers: Fetch feed after creating

CHANGELOG.md, lib/Migration/Version150200Date20210118190652.php
=> Migration: Don't use unsigned for pubdate

CHANGELOG.md, css/content.css
following the recommendations from #1012
=> remove alternating row colors and increase row height

.github/workflows/build-release.yml
This changes the space where secrets are stored, they move to the "release" space.
Releases after this will require manual approval by either me or @SMillerDev
I'm not a hundred percent sure how it will work but I think that it's a good solution.
=> Release environment

CHANGELOG.md, appinfo/info.xml
Changed
- Use signed integer for pubdate (#997)
- revert alternating row colors and increase row height (#1012)
Fixed
- Fetch feed after creation (#1058)
- Implement missing item purger (#1063)
- Update FeedIO Response call and add tests
- Improve Psalm tests and dependency definition
=> Release 15.2.0-rc1

CHANGELOG.md, lib/Db/ItemMapperV2.php, lib/Db/NewsMapperV2.php
fixes #1094
@chrbayer would you please test it with PostgreSQL?
SQLite apparently also accepts `true/false` even without a boolean type.
=> fix item purger for PostgreSQL

CHANGELOG.md, Makefile, composer.json, composer.lock
=> Composer: Remove unneeded files in releases

CHANGELOG.md, appinfo/info.xml
Fixed
- Purging error "Undefined index: articlesPerUpdate"
- Clean up install files
=> Release 15.2.1

Makefile
=> .git dir not allowed by App Store

CHANGELOG.md, appinfo/info.xml
Fixed
- Remove a .git dir from the release archive
=> Release 15.2.2

.github/ISSUE_TEMPLATE/bug_report.md
Fixed some typos and auto-collapse the code blocks
=> Cleanup bug report template

CHANGELOG.md, lib/Db/ItemMapperV2.php
=> fix result ordering for purging query

CHANGELOG.md, appinfo/info.xml
Changed
- DB: Remove unused fields and migrate last_modified to signed, to support dates before 1970
Fixed
- Release: create signature file (#1117)
- Articles are refetched after purging leaving them unread again (#1122)
=> Release 15.3.0

.github/workflows/build-release.yml
=> use 'github.workspace' in release action

CHANGELOG.md, appinfo/info.xml
Changed
- re-release of 15.3.0
=> Release 15.3.1-rc1

.github/workflows/build-release.yml
=> Release: revert back to cd

CHANGELOG.md, appinfo/info.xml
Changed
- re-re-release of 15.3.0
=> Release 15.3.1-rc2

.github/workflows/build-release.yml
=> Actions: Setup app before release

CHANGELOG.md, appinfo/info.xml
Changed
- re-re-re-release of 15.3.0
hopefully the last test
=> Release 15.3.1-rc3

CHANGELOG.md, appinfo/info.xml
Changed
- New release without any changes compared to 15.3.0
=> Release 15.3.1

CHANGELOG.md, lib/Db/ItemMapperV2.php
=> fix refetching of purged articles

CHANGELOG.md, appinfo/info.xml
Fixed
- Missing certificate in signature file (#1143)
- Refetching of already read articles after purging (#1142)
=> Release 15.3.2-rc1

bin/tools/file_from_env.php
=> improve file_from_env script

.github/workflows/build-release.yml
=> Fix release flow

CHANGELOG.md, appinfo/info.xml
Fixed
- Missing certificate in signature file (#1143)
=> Release 15.3.2-rc2

CHANGELOG.md, appinfo/info.xml
=> Release 15.3.2

CHANGELOG.md, appinfo/info.xml
- Item list not using ID for offset 2 (#1200)
=> Release 15.4.0-beta2

CHANGELOG.md, composer.json, composer.lock, lib/Command/Config/FeedAdd.php, lib/Config/FetcherConfig.php, lib/Config/LegacyConfig.php, lib/Controller/FeedApiController.php, lib/Controller/FeedController.php, lib/Controller/FolderApiController.php, lib/Controller/FolderController.php, lib/Cron/UpdaterJob.php, lib/Db/EntityJSONSerializer.php, lib/Db/Item.php, lib/Db/ItemMapperV2.php, lib/Fetcher/Client/FeedIoClient.php, lib/Fetcher/FeedFetcher.php, lib/Service/Exceptions/ServiceException.php, lib/Service/FeedServiceV2.php, lib/Service/ImportService.php, lib/Service/ItemServiceV2.php, lib/Service/StatusService.php
Probably doesn't fix anything yet, but it's nice to have the checks
=> Make PHPstan stricter

CHANGELOG.md, lib/Command/Debug/FeedItemList.php, lib/Command/Debug/ItemList.php, tests/Unit/Command/FeedItemListTest.php, tests/Unit/Command/FolderItemListTest.php, tests/Unit/Command/ItemListTest.php, tests/Unit/Config/FetcherConfigTest.php
Just some extra unittests to catch regressions
=> chore: Improve test coverage

AUTHORS.md, CHANGELOG.md, lib/Db/ItemMapperV2.php, tests/Unit/Db/ItemMapperPaginatedTest.php, tests/integration/items.bats
=> DB: Allow negative limits

CHANGELOG.md, lib/Db/ItemMapperV2.php, tests/Unit/Db/ItemMapperAfterTest.php, tests/Unit/Db/ItemMapperPaginatedTest.php
=> DB: Use boolean parameter for unread/starred

CHANGELOG.md, appinfo/info.xml
Fixed
- Allow negative limits (#1275)
- Use boolean to check bool fields (#1278)
=> Release 15.4.0-beta4

CHANGELOG.md
=> Update changelog for 15.4.0-rc1

appinfo/info.xml
Fixed
- Check category label for null (#1282)
- Do not return non-matching search items
- Resolve an issue with webservices missing items
=> Release 15.4.0-rc1

.github/workflows/build-release.yml
=> delete key and crt after the last step

CHANGELOG.md
=> prepare changelog

CHANGELOG.md, appinfo/info.xml
See previous notes for a full overview.
- Fix search results not redirecting to the news app
=> Release 15.4.0

composer.lock
=> revert composer change

CHANGELOG.md, appinfo/info.xml
Fixed
- revert accidentally merged dependency updates (#1332)
=> Release 15.4.2

CHANGELOG.md
=> update changelog 15.4.4

templates/admin.php
=> fix broken link

templates/admin.php
=> backport link fix

templates/admin.php
=> fix missing "

CHANGELOG.md, appinfo/info.xml
Fixed
- newestId does not return newest ID but last updated (#1339)
=> Release 15.4.5

CHANGELOG.md, lib/Db/ItemMapperV2.php, tests/Unit/Db/ItemMapperAfterTest.php, tests/Unit/Db/ItemMapperTest.php
=> db: no longer order by items.last_modified

appinfo/info.xml, docs/api/api-v1.md, docs/developer.md, mkdocs.yml
=> add admin docs page, document removal of command

appinfo/routes.php
=> remove routes

CHANGELOG.md, appinfo/info.xml
After upgrading to v16.0.0-beta2 I've noticed two `Repair step 'OCA\\News\\Migration\\xyz' is unknown` errors in the log.
(follow-up for #1288)
<details><summary>Log entries</summary>
```json
{"reqId":"UO3QCCS4JJKeqAOmnKXg","level":3,"time":"2021-06-04T14:53:40+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":{"Exception":"Exception","Message":"Repair step 'OCA\\News\\Migration\\MigrateConfig' is unknown","Code":0,"Trace":[{"file":"/var/www/cloud/lib/private/legacy/OC_App.php","line":1047,"function":"addStep","class":"OC\\Repair","type":"->","args":["OCA\\News\\Migration\\MigrateConfig"]},{"file":"/var/www/cloud/lib/private/legacy/OC_App.php","line":996,"function":"executeRepairSteps","class":"OC_App","type":"::","args":["*** sensitive …
```
=> removed reference for deleted repair-steps

CHANGELOG.md, appinfo/info.xml
Changed
- added feed search (#1402)
Fixed
- removed reference for deleted repair-steps (#1399)
- Fix NotNullConstraintViolation when sharing news items with users (#1406)
=> Release 16.0.0-beta3

.github/workflows/api-integration-tests.yml, .github/workflows/api-php-static-code-check.yml, .github/workflows/api-php-tests.yml, .github/workflows/build-release.yml, .github/workflows/frontend-nodejs-tests.yml, .github/workflows/post-merge-tasks.yml, tests/Unit/Db/FeedMapperTest.php, tests/Unit/Db/FolderMapperTest.php, tests/Unit/Db/ItemMapperAfterTest.php, tests/Unit/Db/ItemMapperPaginatedTest.php, tests/Unit/Db/ItemMapperTest.php, tests/Unit/Db/MapperTestUtility.php
- raise the NC server version to the current stable
- fix the integration tests by pinning the MariaDB version since the latest released v10.6 is not yet supported
(see nextcloud/server#25474 for more info)
=> Update NC version and pin MariaDB version for CI

AUTHORS.md, CHANGELOG.md, appinfo/info.xml
Fixed
- fix link-icon-overlap in mobile-view (#1579)
=> Release 17.0.0

.github/workflows/api-integration-tests.yml, .github/workflows/api-php-static-code-check.yml, .github/workflows/api-php-tests.yml, .github/workflows/build-release.yml, .github/workflows/frontend-nodejs-tests.yml, .github/workflows/post-merge-tasks.yml, lib/Command/ExploreGenerator.php
update builds to latest-ish PHP and latest NC
=> chore: update CI

composer.json, composer.lock
=> allow support for php 8.1

CHANGELOG.md, appinfo/info.xml
- Drop support for Nextcloud 21
=> Release 18.0.0-beta1

CONTRIBUTING.md
=> Fix broken links in contributing guide

CHANGELOG.md, lib/Fetcher/FeedFetcher.php
=> Use rawurlencode as it encodes spaces correctly as %20

CHANGELOG.md, appinfo/info.xml
- Change shortcut descriptions. (#1669)
=> Release 18.0.0

docs/api/api-v1.md
only one h1 is allowed with the material theme
=> [docs] fix headers in API v1

AUTHORS.md, CHANGELOG.md, appinfo/info.xml
Fixed
- Fix only one item marked as read by Feed API (#1687)
=> Release 18.0.1-beta1

AUTHORS.md, CHANGELOG.md, appinfo/info.xml
Fixed
- Fix no item marked as read by Folder API due to mismatch in parameter name (#1703)
=> Release 18.0.1-beta2

CHANGELOG.md, appinfo/info.xml
Fixed
- Fix import of items when feed does not exist (#1742)
- Fix malformed feeds (without GUIDs) stopping the update process (#1738)
=> Release 18.0.1-beta3

.github/workflows/api-php-static-code-check.yml, CHANGELOG.md, appinfo/info.xml, lib/Service/ImportService.php
No major changes since the beta versions.
=> Release 18.0.1

.github/workflows/api-integration-tests.yml, .github/workflows/api-php-static-code-check.yml, .github/workflows/api-php-tests.yml, .github/workflows/build-release.yml, .github/workflows/frontend-nodejs-tests.yml, .github/workflows/post-merge-tasks.yml, Makefile
This is removed in the last NC versions
=> integration test: no app:check-code on new NC

CHANGELOG.md, css/content.css
Discussion: https://github.com/nextcloud/news/discussions/1794
=> Fix doubling the height of the content area

CHANGELOG.md, appinfo/info.xml
###Fixed
- Fix export of unread and starred articles failing due to postgres error (#1839, #1249)
- Fix broken API v1.3 (#1841)
=> Release 18.1.1-beta1

CHANGELOG.md, appinfo/info.xml
No major changes since 18.1.1-beta1.
=> Release 18.1.1

js/app/Config.js, src/components/AdminSettings.vue
1. Spelling unification in Transifex.
2. Correct a typo.
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>
=> l10n: Spelling unification and correct a typo

src/components/AdminSettings.vue
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>
=> l10n: Spelling unification

CHANGELOG.md, appinfo/info.xml
Fix for the read all function and spelling fixes.
=> Release 18.2.0-beta2

CHANGELOG.md, appinfo/info.xml
Fixed
- Fix the highlighted item when reverse ordering is selected (#1838)
=> Release 18.2.0

CHANGELOG.md, appinfo/info.xml
Changed
- New administrator setting for deleting unread items automatically (#1931)
=> Release 18.3.0-beta1

CHANGELOG.md, appinfo/info.xml
Fixed
- Remove setting for minimum purge interval since it is not used.
=> Release 18.3.0

CHANGELOG.md, css/content.css, js/directive/NewsScroll.js, templates/index.php
Fixes:
- Mark as read on scroll
- Compact article title bar floating in wrong place
=> NC25 compatibility tweaks

CHANGELOG.md, appinfo/info.xml
Fixed
- Fixed various keyboard navigation issues (#1953)
- Fix cron job warning notification layout on NC25 (#1953)
=> Release 19.0.0-beta2

CHANGELOG.md, appinfo/info.xml
Fixed
- Fix nested scrollbars in navigation (#411, #1958)
=> Release 19.0.0

CHANGELOG.md, appinfo/info.xml
Changed
- Dependency updates
I thought in between we could release a small update only containing translation and dep. updates.
=> Release 19.0.1

src/components/AdminSettings.vue
Signed-off-by: Sean Molenaar <SMillerDev@users.noreply.github.com>
=> AdminSettings: add JSDoc parameters

CHANGELOG.md, appinfo/info.xml
Release of 21.0.0 - no notable changes since the beta release
=> Release 21.0.0

CHANGELOG.md, appinfo/info.xml
Changed
- Remove unused background job OCA\News\Cron\Updater (#2137)
- Add info card to the admin settings, showing last job execution (#2141)
=> Release 21.1.0-beta1

CHANGELOG.md, appinfo/info.xml
No notable changes compared 21.1.0-beta1
=> Release 21.1.0

CHANGELOG.md
Changed
- Use httpLastModified field for If-Modified-Since header when fetching feed updates (#2119)
=> Release 21.2.0-beta1

tests/updater/update.bats
* Resolves: # 
add more sleep commands to the updater tests to prevent "race conditions"
=> add more sleep commands

.github/workflows/api-integration-tests.yml, .github/workflows/api-php-static-code-check.yml, .github/workflows/api-php-tests.yml, .github/workflows/build-release.yml, .github/workflows/frontend-nodejs-tests.yml, .github/workflows/post-merge-tasks.yml, .github/workflows/updater-test.yml
* Resolves: # 
add testing on stable27
=> add testing on stable27

.github/workflows/api-php-tests.yml, CHANGELOG.md, appinfo/info.xml
Changed
- Support deflate and gzip compression for HTTP response bodies (#2269)
- Broke apart old FAQ into different guides. Deprecated old FAQ (#2285)
=> Release 22.0.0

CONTRIBUTING.md
=> Fix link to not existing faq

CHANGELOG.md, appinfo/info.xml
No major changes compared to 24.0.0-beta1.
=> Release 24.0.0

Makefile, lib/Db/ItemMapperV2.php
Try to fix the dbal deprecations
=> fix dbal deprecations

package-lock.json
* Resolves: # 
running npm audit fix, dependabot seems not able to handle that
=> npm security fixes

src/routes/index.ts
* Relates: https://github.com/nextcloud/news/issues/2507
I think this will create a better default for users.
=> fix: default to unread page

CHANGELOG.md, appinfo/info.xml, tests/command/feeds.bats
- Changed default page when starting app (#2515)
- Fix search support for Nextcloud 28 (#2432)
And lot's of dependency updates for js.
=> Release 25.0.0-alpha3

lib/Command/Debug/FolderRead.php
=> FolderRead: add type declarations

CHANGELOG.md, appinfo/info.xml
Works when force enabling already
=> chore: support Nextcloud 29

docs/admin.md, docs/api/api-v1-2.md, docs/api/api-v1-3.md, docs/api/api-v2.md, docs/developer.md, docs/features/customCSS.md, docs/features/integration.md, docs/features/plugins.md, docs/features/themes.md, docs/troubleshooting.md, mkdocs.yml
I applied all findings returned by `markdownlint` for the Markdown docs files of this project to enhance the readability of the code.
I also enabled the the **syntax highlighting** for the code blocks to further enhance the readability.
Until now the docs where not easy to read in dark(er) environments so I also enabled the automatic theme switcher based on the browser's `prefers-color-scheme` header.
=> enhance docs readability

CHANGELOG.md, appinfo/info.xml
- Improve layout of feed item row (#2569)
- Reset content scroll position when feed item is changed (#2569)
- Fix link to feed in article header (#2569)
=> Release 25.0.0-alpha6

.github/workflows/api-integration-tests.yml, .github/workflows/updater-test.yml
=> update bats to latest release

docs/admin.md
=> Add section about OCC

lib/Explore/feeds/feeds.en.json
=> update the nextcloud blog url

css/navigation.scss
I am sure this can be done more professionally - but this is at least usable as opposed to the current useless situation of the app for current NextCloud version
Only edits to CSS to make the news app usable on the NextCloud Web frontend. 
=> Cosmetics: Attempt to make news App minimally usable in NC 29

CHANGELOG.md, src/main.js
* Resolves: #2738
Disable shortkeys in input and textarea fields.
=> fix: Keyboard shortcuts are active even when searching

CHANGELOG.md, css/navigation.scss
* Resolves: styleint github action
fix formatting
=> fix: make styleint happy

src/components/modals/HelpModal.vue
=> chore(i18n): improved grammar

src/components/feed-display/FeedItemDisplayList.vue
* Related: #2850
listOrdering not initialized properly
=> Hotfix for #2850

CHANGELOG.md, appinfo/info.xml
Changed
- Small visual changes introduced by Nextcloud.
Fixed
- switching feeds with key navigation does not work with top level feeds (#2863)
- proper handling when adding or deleting feeds and folders (#2863)
- Article not marked as read on middle-clicking on "Open website" icon (#2863)
=> Release 25.0.0-alpha14

CHANGELOG.md, appinfo/info.xml, lib/Command/Config/OpmlImport.php, lib/Service/OpmlService.php, lib/Utility/OPMLImporter.php, tests/Unit/Service/OPMLServiceTest.php
Allow users to import OPML files through the commandline.
=> feat: Add OPML import in CLI

package-lock.json, package.json, src/types/nextcloud__router.d.ts, tests/javascript/unit/components/routes/Explore.spec.ts
Update dependency @nextcloud/router to 3.0.1
Update dependency @nextcloud/dialogs to 6.0.1
=> deps: update @nextcloud/router to 3.0.1 and @nextcloud/dialogs to 6.0.1

CHANGELOG.md, src/components/Sidebar.vue, src/components/feed-display/FeedItemDisplay.vue, src/components/feed-display/FeedItemRow.vue
* Related: #2919 
Fix accessibility in article list and small fixes suggested by firefox WAVE plugin.
=> small accessibility fixes

tests/command/feeds.bats, tests/command/items.bats
=> reactivate tests

CHANGELOG.md, appinfo/info.xml
- Set maximum delay for updates to "in one day" (#3015)
- add an information list for feeds that displays data such as last or next update dates (#3021)
- OPML import use text field for title if title field is missing (#3016)
=> Release 25.2.0-beta.2

docs/user.md, mkdocs.yml, src/components/Sidebar.vue
* Related: #3000
* Add user.md to mkdocs
* Add documentation link button to settings section
* Add subscribe form description
=> User documentation

CHANGELOG.md, appinfo/info.xml
No additional changes since the beta releases.
=> Release 25.2.1

CHANGELOG.md, appinfo/info.xml
* Resolves: #3085
Enable support for Nextcloud 31
=> Enable support for Nextcloud 31

CHANGELOG.md
* Resolves: # 
- Enable support for php 8.4 (#3038)
- Enable support for Nextcloud 31 (#3089)
=> Release 25.3.0-beta.1

lib/Fetcher/FeedFetcher.php
* Resolves: # 
->withPath does not modify the variable
=> small fix for #3105

CHANGELOG.md, appinfo/info.xml
No major changes since the beta releases.
=> Release 25.3.0

CHANGELOG.md, appinfo/info.xml
- Sort feeds case-insensitive (#3125)
- Fix proxy configuration without schema -> default http:// (#3115)
=> Release 25.3.1

package-lock.json, package.json, tests/javascript/unit/setup.ts
- nextcloud/vue 8.24.0 needs appName in javascript unit test setup
=> builddeps: update @nextcloud/vue 8.24.0

src/components/Sidebar.vue, src/components/routes/Feed.vue, src/components/routes/Folder.vue, src/components/routes/Starred.vue, src/components/routes/Unread.vue, src/store/app.ts
Related: #2916 
This PR fixes a few bugs that are relevant for the vue3 migration and the nextcloud/vue v9 update.
=> Preparation for the upcoming nextcloud/vue v9 update

CHANGELOG.md, appinfo/info.xml
Fixed
-  Item list not updated by automatic or manual refresh (#3155)
=> Release 26.0.0-beta.2

src/App.vue, src/components/Sidebar.vue, src/components/feed-display/FeedItemDisplay.vue, src/components/feed-display/FeedItemDisplayList.vue, src/components/modals/FeedInfoTable.vue, src/components/routes/All.vue, src/components/routes/Explore.vue, src/components/routes/Feed.vue, src/components/routes/Folder.vue, src/components/routes/Starred.vue, src/components/routes/Unread.vue
With @nextcloud/stylelint-config 3.1.0 new stylelint warnings appeared.
=> fix: stylelint warnings from update @nextcloud/stylelint-config 3.1.0

.github/workflows/build-release.yml
update all actions in the release workflow
=> update all actions in the release workflow

CHANGELOG.md, composer.json, composer.lock
* Resolves: # 
I think we can check if this works now.
=> switch to php-feed-io/feed-io

CHANGELOG.md, appinfo/info.xml
- add refresh button to list header (#3259)
=> Release 26.1.0

package.json
I investigated the npm dependabot problem local with the dependabot-cli.
Dependabot uses the oldest npm version when using "npm": "^10.0.0", which seems to have a problem. Corepack gets a network error when using 10.0.0.
```
updater | 2025/08/11 09:19:01 INFO Installing "npm@10.0.0"
updater | 2025/08/11 09:19:01 INFO Started process PID: 1389 with command: {} corepack install npm@10.0.0 --global --cache-only {}
proxy | 2025/08/11 09:19:01 [002] GET https://registry.npmjs.org:443/npm/-/npm-10.0.0.tgz
proxy | 2025/08/11 09:19:01 [002] 200 https://registry.npmjs.org:443/npm/-/npm-10.0.0.tgz
proxy | 2025/08/11 09:19:02 [004] GET https://registry.npmjs.org:443/npm/10.0.0
proxy | 2025/08/11 09:19:03 [004] 200 https://registry.npmjs.org:443/npm/10.0.0
updater | 2025/08/11 09:19:03 INFO Process …
```
=> fix npm dependabot issues

composer.json, composer.lock
* Resolves: # 
update feed-io and other composer packages
=> update php packages
